"""Add DC info to District

Revision ID: 0165ef25f079
Revises: 1be3dc4a9bfd
Create Date: 2026-07-02 16:41:42.146298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0165ef25f079'
down_revision: Union[str, Sequence[str], None] = '1be3dc4a9bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('district_table', sa.Column('dc_name', sa.String(length=100), nullable=True))
    op.add_column('district_table', sa.Column('dc_email', sa.String(length=100), nullable=True))
    op.add_column('district_table', sa.Column('dc_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('district_table', 'dc_phone')
    op.drop_column('district_table', 'dc_email')
    op.drop_column('district_table', 'dc_name')
    # ### end Alembic commands ###

