"""make_updated_at_nullable

Revision ID: 0454a62a6223
Revises: 1fd6acf3575d
Create Date: 2026-06-13 23:28:11.262529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0454a62a6223'
down_revision: Union[str, Sequence[str], None] = '1fd6acf3575d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('LMS_table', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               server_default=None)
    op.alter_column('candidate_table', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               server_default=None)
    op.alter_column('nseit_request_table', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               server_default=None)
               
    # Set existing rows' updated_at to NULL since no action other than creation has been taken on them yet
    op.execute('UPDATE "LMS_table" SET updated_at = NULL')
    op.execute('UPDATE candidate_table SET updated_at = NULL')
    op.execute('UPDATE nseit_request_table SET updated_at = NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nseit_request_table', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('candidate_table', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               server_default=sa.text('now()'))
    op.alter_column('LMS_table', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               server_default=sa.text('now()'))
    # ### end Alembic commands ###
