"""initial

Revision ID: 06406fff49e1
Revises: 
Create Date: 2026-06-12 11:12:26.629889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06406fff49e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lms_remark_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('R_id', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=1000), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('admin_by_id', sa.Integer(), nullable=True),
    sa.Column('candidate_by_id', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['R_id'], ['LMS_table.id'], ),
    sa.ForeignKeyConstraint(['admin_by_id'], ['user_login_table.id'], ),
    sa.ForeignKeyConstraint(['candidate_by_id'], ['candidate_login_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nseit_request_remark_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('R_Id', sa.Integer(), nullable=False),
    sa.Column('remark', sa.String(length=1000), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('admin_by_id', sa.Integer(), nullable=True),
    sa.Column('candidate_by_id', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['R_Id'], ['nseit_request_table.id'], ),
    sa.ForeignKeyConstraint(['admin_by_id'], ['user_login_table.id'], ),
    sa.ForeignKeyConstraint(['candidate_by_id'], ['candidate_login_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nseit_request_remark_table')
    op.drop_table('lms_remark_table')
    # ### end Alembic commands ###
