"""add_l1_and_reactivation_tables

Revision ID: 07f3092bf081
Revises: 29b37984debf
Create Date: 2026-06-17 19:48:59.474950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f3092bf081'
down_revision: Union[str, Sequence[str], None] = '29b37984debf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('l1_registration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_code', sa.String(), nullable=False),
    sa.Column('district_id', sa.String(length=20), nullable=False),
    sa.Column('station_id', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=False),
    sa.Column('operator_name', sa.String(), nullable=True),
    sa.Column('operator_id', sa.String(), nullable=True),
    sa.Column('model_type', sa.String(), nullable=False),
    sa.Column('software_version', sa.String(), nullable=False),
    sa.Column('uv_id', sa.String(), nullable=False),
    sa.Column('uv_password', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district_table.district_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_l1_registration_requests_id'), 'l1_registration_requests', ['id'], unique=False)
    op.create_index(op.f('ix_l1_registration_requests_request_code'), 'l1_registration_requests', ['request_code'], unique=True)
    op.create_table('l1_registration_remark_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_code', sa.String(), nullable=False),
    sa.Column('remark', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('user_role', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_code'], ['l1_registration_requests.request_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_l1_registration_remark_history_request_code'), 'l1_registration_remark_history', ['request_code'], unique=False)
    op.create_table('operator_reactivation_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_code', sa.String(length=50), nullable=False),
    sa.Column('dc_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.String(length=20), nullable=False),
    sa.Column('operator_count', sa.Integer(), nullable=False),
    sa.Column('training_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['dc_id'], ['user_login_table.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['district_id'], ['district_table.district_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_reactivation_requests_created_at'), 'operator_reactivation_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_operator_reactivation_requests_request_code'), 'operator_reactivation_requests', ['request_code'], unique=True)
    op.create_index(op.f('ix_operator_reactivation_requests_status'), 'operator_reactivation_requests', ['status'], unique=False)
    op.create_table('reactivation_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_code', sa.String(length=50), nullable=False),
    sa.Column('doc_type', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=250), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_code'], ['operator_reactivation_requests.request_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reactivation_documents_request_code'), 'reactivation_documents', ['request_code'], unique=False)
    op.create_table('reactivation_operators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_code', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('operator_name', sa.String(length=150), nullable=False),
    sa.Column('registrar_code', sa.String(length=50), nullable=True),
    sa.Column('ea_code', sa.String(length=50), nullable=True),
    sa.Column('user_code', sa.String(length=50), nullable=True),
    sa.Column('certificate_number', sa.String(length=100), nullable=True),
    sa.Column('lms_certificate_id', sa.String(length=100), nullable=True),
    sa.Column('operator_mobile', sa.String(length=20), nullable=False),
    sa.Column('email_id', sa.String(length=100), nullable=True),
    sa.Column('aadhaar_number', sa.String(length=20), nullable=True),
    sa.Column('certification_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(length=250), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['request_code'], ['operator_reactivation_requests.request_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reactivation_operators_request_code'), 'reactivation_operators', ['request_code'], unique=False)
    op.create_table('reactivation_remark_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_code', sa.String(length=50), nullable=False),
    sa.Column('remark_history', sa.TEXT(), nullable=False),
    sa.Column('sender_role', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_code'], ['operator_reactivation_requests.request_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reactivation_remark_history_request_code'), 'reactivation_remark_history', ['request_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reactivation_remark_history_request_code'), table_name='reactivation_remark_history')
    op.drop_table('reactivation_remark_history')
    op.drop_index(op.f('ix_reactivation_operators_request_code'), table_name='reactivation_operators')
    op.drop_table('reactivation_operators')
    op.drop_index(op.f('ix_reactivation_documents_request_code'), table_name='reactivation_documents')
    op.drop_table('reactivation_documents')
    op.drop_index(op.f('ix_operator_reactivation_requests_status'), table_name='operator_reactivation_requests')
    op.drop_index(op.f('ix_operator_reactivation_requests_request_code'), table_name='operator_reactivation_requests')
    op.drop_index(op.f('ix_operator_reactivation_requests_created_at'), table_name='operator_reactivation_requests')
    op.drop_table('operator_reactivation_requests')
    op.drop_index(op.f('ix_l1_registration_remark_history_request_code'), table_name='l1_registration_remark_history')
    op.drop_table('l1_registration_remark_history')
    op.drop_index(op.f('ix_l1_registration_requests_request_code'), table_name='l1_registration_requests')
    op.drop_index(op.f('ix_l1_registration_requests_id'), table_name='l1_registration_requests')
    op.drop_table('l1_registration_requests')
    # ### end Alembic commands ###
