"""Change is_active and has_changed_password to Integer

Revision ID: 0b158e3b72d6
Revises: f311e745dfaf
Create Date: 2026-07-13 13:50:29.937462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b158e3b72d6'
down_revision: Union[str, Sequence[str], None] = 'f311e745dfaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_login_table', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None)
    op.alter_column('user_login_table', 'has_changed_password',
               existing_type=sa.BOOLEAN(),
               server_default=None)

    op.alter_column('user_login_table', 'is_active',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               postgresql_using='is_active::integer',
               existing_nullable=False,
               server_default='1')
    op.alter_column('user_login_table', 'has_changed_password',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               postgresql_using='has_changed_password::integer',
               existing_nullable=False,
               server_default='0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_login_table', 'has_changed_password',
               existing_type=sa.Integer(),
               server_default=None)
    op.alter_column('user_login_table', 'is_active',
               existing_type=sa.Integer(),
               server_default=None)
               
    op.alter_column('user_login_table', 'has_changed_password',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               postgresql_using='has_changed_password::boolean',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_login_table', 'is_active',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               postgresql_using='is_active::boolean',
               existing_nullable=False)
    # ### end Alembic commands ###
