"""Add completed_at to L2RegistrationRequest

Revision ID: 1be3dc4a9bfd
Revises: d8f0377d4216
Create Date: 2026-06-29 07:19:24.628023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1be3dc4a9bfd'
down_revision: Union[str, Sequence[str], None] = 'd8f0377d4216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_status',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.drop_index(op.f('ix_credential_requests_created_at'), table_name='credential_requests')
    op.drop_index(op.f('ix_credential_requests_request_code'), table_name='credential_requests')
    op.drop_index(op.f('ix_credential_requests_status'), table_name='credential_requests')
    op.drop_table('credential_requests')
    op.drop_index(op.f('ix_noc_requests_created_at'), table_name='noc_requests')
    op.drop_index(op.f('ix_noc_requests_id'), table_name='noc_requests')
    op.drop_index(op.f('ix_noc_requests_request_code'), table_name='noc_requests')
    op.drop_index(op.f('ix_noc_requests_status'), table_name='noc_requests')
    op.drop_table('noc_requests')
    op.drop_index(op.f('ix_approval_history_id'), table_name='approval_history')
    op.drop_table('approval_history')
    op.drop_table('districts')
    op.drop_index(op.f('ix_station_kit_details_id'), table_name='station_kit_details')
    op.drop_table('station_kit_details')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.add_column('l2_registration_requests', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('l2_registration_requests', 'completed_at')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('DC', 'CHIPS_ADMIN', name='userrole'), autoincrement=False, nullable=False),
    sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('users_district_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('station_kit_details',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('kit_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('station_kit_details_district_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('station_kit_details_pkey')),
    sa.UniqueConstraint('kit_number', name=op.f('station_kit_details_kit_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('station_id', name=op.f('station_kit_details_station_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_station_kit_details_id'), 'station_kit_details', ['id'], unique=False)
    op.create_table('districts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('districts_pkey')),
    sa.UniqueConstraint('name', name=op.f('districts_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('approval_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action_taken', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['action_by_user_id'], ['users.id'], name=op.f('approval_history_action_by_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('approval_history_pkey'))
    )
    op.create_index(op.f('ix_approval_history_id'), 'approval_history', ['id'], unique=False)
    op.create_table('noc_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('operator_unique_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('operator_first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('operator_middle_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('operator_last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('submitted_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ASSIGNED', 'REVERTED', 'REAPPLIED', name='requeststatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('revert_reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('remarks_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('noc_requests_district_id_fkey')),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('noc_requests_submitted_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('noc_requests_pkey'))
    )
    op.create_index(op.f('ix_noc_requests_status'), 'noc_requests', ['status'], unique=False)
    op.create_index(op.f('ix_noc_requests_request_code'), 'noc_requests', ['request_code'], unique=True)
    op.create_index(op.f('ix_noc_requests_id'), 'noc_requests', ['id'], unique=False)
    op.create_index(op.f('ix_noc_requests_created_at'), 'noc_requests', ['created_at'], unique=False)
    op.create_table('credential_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('request_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('operator_first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('operator_middle_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('operator_last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('operator_phone', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('operator_email', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('district_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('submitted_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ASSIGNED', 'REVERTED', 'REAPPLIED', name='requeststatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('generated_login_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('generated_password_raw', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('revert_reason', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('remarks_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], name=op.f('credential_requests_district_id_fkey')),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], name=op.f('credential_requests_submitted_by_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('credential_requests_pkey')),
    sa.UniqueConstraint('generated_login_id', name=op.f('credential_requests_generated_login_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_credential_requests_status'), 'credential_requests', ['status'], unique=False)
    op.create_index(op.f('ix_credential_requests_request_code'), 'credential_requests', ['request_code'], unique=True)
    op.create_index(op.f('ix_credential_requests_created_at'), 'credential_requests', ['created_at'], unique=False)
    op.drop_table('master_status')
    # ### end Alembic commands ###
