"""add_l2_operator_activation_station_id_tables

Revision ID: 1cee02034d17
Revises: 07f3092bf081
Create Date: 2026-06-17 23:03:39.639849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cee02034d17'
down_revision: Union[str, Sequence[str], None] = '07f3092bf081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('l2_registration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_no', sa.String(length=20), nullable=True),
    sa.Column('dc_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.String(length=20), nullable=True),
    sa.Column('client_version', sa.String(length=50), nullable=False),
    sa.Column('new_station_id', sa.String(length=50), nullable=False),
    sa.Column('ea_code', sa.String(length=50), nullable=False),
    sa.Column('reg_code', sa.String(length=50), nullable=False),
    sa.Column('new_machine_id', sa.String(length=50), nullable=False),
    sa.Column('client_type', sa.String(length=50), nullable=False),
    sa.Column('old_station_id', sa.String(length=50), nullable=True),
    sa.Column('reason_for_l2_registration', sa.Text(), nullable=True),
    sa.Column('old_machine_id', sa.String(length=50), nullable=True),
    sa.Column('tech_center_remarks', sa.Text(), nullable=True),
    sa.Column('operator_name', sa.String(length=100), nullable=False),
    sa.Column('operator_id', sa.String(length=50), nullable=False),
    sa.Column('unique_id', sa.String(length=50), nullable=False),
    sa.Column('block', sa.String(length=100), nullable=False),
    sa.Column('address_of_govt_premises', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('uidai_remarks', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dc_id'], ['user_login_table.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['district_table.district_code'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user_login_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_no')
    )
    op.create_index(op.f('ix_l2_registration_requests_dc_id'), 'l2_registration_requests', ['dc_id'], unique=False)
    op.create_index(op.f('ix_l2_registration_requests_district_id'), 'l2_registration_requests', ['district_id'], unique=False)
    op.create_index(op.f('ix_l2_registration_requests_id'), 'l2_registration_requests', ['id'], unique=False)
    op.create_index(op.f('ix_l2_registration_requests_status'), 'l2_registration_requests', ['status'], unique=False)
    op.create_index(op.f('ix_l2_registration_requests_submitted_at'), 'l2_registration_requests', ['submitted_at'], unique=False)
    op.create_table('operator_activation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_no', sa.String(length=20), nullable=True),
    sa.Column('dc_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('name_as_per_aadhaar', sa.String(length=120), nullable=False),
    sa.Column('registrar_code', sa.String(length=50), nullable=True),
    sa.Column('ea_code', sa.String(length=50), nullable=True),
    sa.Column('user_code', sa.String(length=50), nullable=True),
    sa.Column('nseit_certificate_number', sa.String(length=50), nullable=True),
    sa.Column('operator_mobile', sa.String(length=15), nullable=False),
    sa.Column('primary_email', sa.String(length=120), nullable=True),
    sa.Column('operator_aadhaar', sa.String(length=4), nullable=True),
    sa.Column('nseit_certification_date', sa.DateTime(), nullable=True),
    sa.Column('nseit_certificate_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remark_to_uidai', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dc_id'], ['user_login_table.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['district_table.district_code'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user_login_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_no')
    )
    op.create_index(op.f('ix_operator_activation_requests_dc_id'), 'operator_activation_requests', ['dc_id'], unique=False)
    op.create_index(op.f('ix_operator_activation_requests_district_id'), 'operator_activation_requests', ['district_id'], unique=False)
    op.create_index(op.f('ix_operator_activation_requests_id'), 'operator_activation_requests', ['id'], unique=False)
    op.create_index(op.f('ix_operator_activation_requests_reviewed_by'), 'operator_activation_requests', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_operator_activation_requests_status'), 'operator_activation_requests', ['status'], unique=False)
    op.create_index(op.f('ix_operator_activation_requests_submitted_at'), 'operator_activation_requests', ['submitted_at'], unique=False)
    op.create_table('station_id_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_no', sa.String(length=20), nullable=True),
    sa.Column('dc_id', sa.Integer(), nullable=False),
    sa.Column('district_id', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=10), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('user_type_custom_reason', sa.Text(), nullable=True),
    sa.Column('number_of_kits', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('station_id_inserted', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dc_id'], ['user_login_table.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['district_table.district_code'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user_login_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_no')
    )
    op.create_index(op.f('ix_station_id_requests_dc_id'), 'station_id_requests', ['dc_id'], unique=False)
    op.create_index(op.f('ix_station_id_requests_district_id'), 'station_id_requests', ['district_id'], unique=False)
    op.create_index(op.f('ix_station_id_requests_id'), 'station_id_requests', ['id'], unique=False)
    op.create_index(op.f('ix_station_id_requests_status'), 'station_id_requests', ['status'], unique=False)
    op.create_index(op.f('ix_station_id_requests_submitted_at'), 'station_id_requests', ['submitted_at'], unique=False)
    op.create_table('activation_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=40), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['operator_activation_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'doc_type', name='uq_activation_doc_request_doctype')
    )
    op.create_index(op.f('ix_activation_documents_id'), 'activation_documents', ['id'], unique=False)
    op.create_index(op.f('ix_activation_documents_request_id'), 'activation_documents', ['request_id'], unique=False)
    op.create_table('l2_registration_remarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_role', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user_login_table.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['l2_registration_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_l2_registration_remarks_id'), 'l2_registration_remarks', ['id'], unique=False)
    op.create_index(op.f('ix_l2_registration_remarks_request_id'), 'l2_registration_remarks', ['request_id'], unique=False)
    op.create_table('operator_activation_remarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_role', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user_login_table.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['operator_activation_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_activation_remarks_id'), 'operator_activation_remarks', ['id'], unique=False)
    op.create_index(op.f('ix_operator_activation_remarks_request_id'), 'operator_activation_remarks', ['request_id'], unique=False)
    op.create_table('station_id_remarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_role', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user_login_table.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['station_id_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_station_id_remarks_id'), 'station_id_remarks', ['id'], unique=False)
    op.create_index(op.f('ix_station_id_remarks_request_id'), 'station_id_remarks', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_station_id_remarks_request_id'), table_name='station_id_remarks')
    op.drop_index(op.f('ix_station_id_remarks_id'), table_name='station_id_remarks')
    op.drop_table('station_id_remarks')
    op.drop_index(op.f('ix_operator_activation_remarks_request_id'), table_name='operator_activation_remarks')
    op.drop_index(op.f('ix_operator_activation_remarks_id'), table_name='operator_activation_remarks')
    op.drop_table('operator_activation_remarks')
    op.drop_index(op.f('ix_l2_registration_remarks_request_id'), table_name='l2_registration_remarks')
    op.drop_index(op.f('ix_l2_registration_remarks_id'), table_name='l2_registration_remarks')
    op.drop_table('l2_registration_remarks')
    op.drop_index(op.f('ix_activation_documents_request_id'), table_name='activation_documents')
    op.drop_index(op.f('ix_activation_documents_id'), table_name='activation_documents')
    op.drop_table('activation_documents')
    op.drop_index(op.f('ix_station_id_requests_submitted_at'), table_name='station_id_requests')
    op.drop_index(op.f('ix_station_id_requests_status'), table_name='station_id_requests')
    op.drop_index(op.f('ix_station_id_requests_id'), table_name='station_id_requests')
    op.drop_index(op.f('ix_station_id_requests_district_id'), table_name='station_id_requests')
    op.drop_index(op.f('ix_station_id_requests_dc_id'), table_name='station_id_requests')
    op.drop_table('station_id_requests')
    op.drop_index(op.f('ix_operator_activation_requests_submitted_at'), table_name='operator_activation_requests')
    op.drop_index(op.f('ix_operator_activation_requests_status'), table_name='operator_activation_requests')
    op.drop_index(op.f('ix_operator_activation_requests_reviewed_by'), table_name='operator_activation_requests')
    op.drop_index(op.f('ix_operator_activation_requests_id'), table_name='operator_activation_requests')
    op.drop_index(op.f('ix_operator_activation_requests_district_id'), table_name='operator_activation_requests')
    op.drop_index(op.f('ix_operator_activation_requests_dc_id'), table_name='operator_activation_requests')
    op.drop_table('operator_activation_requests')
    op.drop_index(op.f('ix_l2_registration_requests_submitted_at'), table_name='l2_registration_requests')
    op.drop_index(op.f('ix_l2_registration_requests_status'), table_name='l2_registration_requests')
    op.drop_index(op.f('ix_l2_registration_requests_id'), table_name='l2_registration_requests')
    op.drop_index(op.f('ix_l2_registration_requests_district_id'), table_name='l2_registration_requests')
    op.drop_index(op.f('ix_l2_registration_requests_dc_id'), table_name='l2_registration_requests')
    op.drop_table('l2_registration_requests')
    # ### end Alembic commands ###
