"""add_created_at_updated_at

Revision ID: 1fd6acf3575d
Revises: e90a268f1090
Create Date: 2026-06-13 23:16:54.626261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd6acf3575d'
down_revision: Union[str, Sequence[str], None] = 'e90a268f1090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LMS_table', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('LMS_table', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('candidate_table', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('candidate_table', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('nseit_request_table', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('nseit_request_table', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nseit_request_table', 'updated_at')
    op.drop_column('nseit_request_table', 'created_at')
    op.drop_column('candidate_table', 'updated_at')
    op.drop_column('candidate_table', 'created_at')
    op.drop_column('LMS_table', 'updated_at')
    op.drop_column('LMS_table', 'created_at')
    # ### end Alembic commands ###
