"""add foreign keys to master_status

Revision ID: 22c55cbd37ad
Revises: 90585e623d2c
Create Date: 2026-07-08 17:08:51.941980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22c55cbd37ad'
down_revision: Union[str, Sequence[str], None] = '90585e623d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'LMS_table', 'master_status', ['status_code'], ['code'])
    op.create_foreign_key(None, 'candidate_table', 'master_status', ['status_code'], ['code'])
    op.create_foreign_key(None, 'dc_remark_table', 'master_status', ['status_after_code'], ['code'])
    op.create_foreign_key(None, 'l1_registration_remark_history', 'master_status', ['status_after_code'], ['code'])
    op.create_foreign_key(None, 'l1_registration_requests', 'master_status', ['status_code'], ['code'])
    op.create_foreign_key(None, 'l2_registration_remarks', 'master_status', ['status_after_code'], ['code'])
    op.create_foreign_key(None, 'l2_registration_requests', 'master_status', ['status_code'], ['code'])
    op.create_foreign_key(None, 'lms_remark_table', 'master_status', ['status_after_code'], ['code'])
    op.create_foreign_key(None, 'nseit_request_remark_table', 'master_status', ['status_after_code'], ['code'])
    op.create_foreign_key(None, 'nseit_request_table', 'master_status', ['status_code'], ['code'])
    op.create_foreign_key(None, 'operator_activation_remarks', 'master_status', ['status_after_code'], ['code'])
    op.create_foreign_key(None, 'operator_activation_requests', 'master_status', ['status_code'], ['code'])
    op.create_foreign_key(None, 'operator_reactivation_requests', 'master_status', ['status_code'], ['code'])
    op.create_foreign_key(None, 'reactivation_operators', 'master_status', ['status_code'], ['code'])
    op.create_foreign_key(None, 'reactivation_remark_history', 'master_status', ['status_after_code'], ['code'])
    op.create_foreign_key(None, 'station_id_remarks', 'master_status', ['status_after_code'], ['code'])
    op.create_foreign_key(None, 'station_id_requests', 'master_status', ['status_code'], ['code'])
    # ### end Alembic commands ###
def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
