"""Add report_history table

Revision ID: 2392e65dd488
Revises: 0b158e3b72d6
Create Date: 2026-07-16 11:05:20.453893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2392e65dd488'
down_revision: Union[str, Sequence[str], None] = '0b158e3b72d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operator_onboardings_id'), table_name='operator_onboardings')
    op.drop_index(op.f('ix_operator_onboardings_operator_id'), table_name='operator_onboardings')
    op.drop_index(op.f('ix_operator_onboardings_station_id'), table_name='operator_onboardings')
    op.drop_table('operator_onboardings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_onboardings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('operator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('station_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('onboarding_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('ask_kit_working_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('permitted_18_plus', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('remark', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('operator_onboardings_operator_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('operator_onboardings_pkey'))
    )
    op.create_index(op.f('ix_operator_onboardings_station_id'), 'operator_onboardings', ['station_id'], unique=False)
    op.create_index(op.f('ix_operator_onboardings_operator_id'), 'operator_onboardings', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_onboardings_id'), 'operator_onboardings', ['id'], unique=False)
    # ### end Alembic commands ###
