"""initialize_core_chips_and_dc_schemas

Revision ID: 3abd22e6a4a3
Revises: 
Create Date: 2026-06-03 10:58:26.287473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abd22e6a4a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('DC', 'CHIPS_ADMIN', name='userrole'), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('credential_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_first_name', sa.String(length=100), nullable=False),
    sa.Column('operator_middle_name', sa.String(length=100), nullable=True),
    sa.Column('operator_last_name', sa.String(length=100), nullable=False),
    sa.Column('operator_phone', sa.String(length=15), nullable=False),
    sa.Column('operator_email', sa.String(length=150), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('generated_login_id', sa.String(length=100), nullable=True),
    sa.Column('generated_password_raw', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generated_login_id')
    )
    with op.batch_alter_table('credential_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credential_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credential_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credential_requests_status'))
        batch_op.drop_index(batch_op.f('ix_credential_requests_created_at'))

    op.drop_table('credential_requests')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('districts')
    # ### end Alembic commands ###
