"""add_candidate_address_photo_operator_fields

Revision ID: 5d0e09a3f538
Revises: add_status_after_field
Create Date: 2026-06-16 16:39:07.163246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d0e09a3f538'
down_revision: Union[str, Sequence[str], None] = 'add_status_after_field'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_table', sa.Column('address', sa.String(length=500), nullable=True))
    op.add_column('candidate_table', sa.Column('pincode', sa.String(length=10), nullable=True))
    op.add_column('candidate_table', sa.Column('is_existing_operator', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('candidate_table', sa.Column('photo_upload', sa.String(length=255), nullable=True))
    op.add_column('candidate_table', sa.Column('tenth_marksheet_upload', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_table', 'tenth_marksheet_upload')
    op.drop_column('candidate_table', 'photo_upload')
    op.drop_column('candidate_table', 'is_existing_operator')
    op.drop_column('candidate_table', 'pincode')
    op.drop_column('candidate_table', 'address')
    # ### end Alembic commands ###
