"""add_operator_mappings_onboarding

Revision ID: 5d170452c194
Revises: e43fbf38a016
Create Date: 2026-07-21 23:15:51.253424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d170452c194'
down_revision: Union[str, Sequence[str], None] = 'e43fbf38a016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_station_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('mapped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_station_mappings_id'), 'operator_station_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_operator_station_mappings_operator_id'), 'operator_station_mappings', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_station_mappings_station_id'), 'operator_station_mappings', ['station_id'], unique=False)
    op.create_table('operator_onboarding_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.String(length=50), nullable=False),
    sa.Column('onboarding_status', sa.String(length=50), nullable=False),
    sa.Column('onboard_date', sa.Date(), nullable=True),
    sa.Column('ask_kit_working_status', sa.String(length=50), nullable=False),
    sa.Column('permitted_18_plus', sa.String(length=50), nullable=False),
    sa.Column('visit_status', sa.String(length=50), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mapping_id'], ['operator_station_mappings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_onboarding_details_id'), 'operator_onboarding_details', ['id'], unique=False)
    op.create_index(op.f('ix_operator_onboarding_details_mapping_id'), 'operator_onboarding_details', ['mapping_id'], unique=False)
    op.create_index(op.f('ix_operator_onboarding_details_operator_id'), 'operator_onboarding_details', ['operator_id'], unique=False)
    op.create_index(op.f('ix_operator_onboarding_details_station_id'), 'operator_onboarding_details', ['station_id'], unique=False)
    op.alter_column('kit_registration_table', 'machine_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('kit_registration_table', 'laptop_serial_no',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('kit_registration_table', 'laptop_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('kit_registration_table', 'category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_constraint(op.f('kit_registration_table_station_id_key'), 'kit_registration_table', type_='unique')
    op.alter_column('l2_registration_requests', 'new_machine_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('l2_registration_requests', 'old_machine_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('l2_registration_requests', 'operator_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('l2_registration_requests', 'operator_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('l2_registration_requests', 'block',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('l2_registration_requests', 'address_of_govt_premises',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('operators', 'inactive_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('operators', 'security_deposit_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_station_id_requests_station_id_inserted'), 'station_id_requests', type_='unique')
    op.execute('ALTER TABLE user_login_table ALTER COLUMN is_active DROP DEFAULT')
    op.execute('ALTER TABLE user_login_table ALTER COLUMN is_active TYPE BOOLEAN USING (is_active = 1)')
    op.execute('ALTER TABLE user_login_table ALTER COLUMN is_active SET DEFAULT true')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_login_table', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.create_unique_constraint(op.f('uq_station_id_requests_station_id_inserted'), 'station_id_requests', ['station_id_inserted'], postgresql_nulls_not_distinct=False)
    op.alter_column('operators', 'security_deposit_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('operators', 'inactive_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('l2_registration_requests', 'address_of_govt_premises',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('l2_registration_requests', 'block',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('l2_registration_requests', 'operator_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('l2_registration_requests', 'operator_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('l2_registration_requests', 'old_machine_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('l2_registration_requests', 'new_machine_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_unique_constraint(op.f('kit_registration_table_station_id_key'), 'kit_registration_table', ['station_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('kit_registration_table', 'category',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('kit_registration_table', 'laptop_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('kit_registration_table', 'laptop_serial_no',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('kit_registration_table', 'machine_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_operator_onboarding_details_station_id'), table_name='operator_onboarding_details')
    op.drop_index(op.f('ix_operator_onboarding_details_operator_id'), table_name='operator_onboarding_details')
    op.drop_index(op.f('ix_operator_onboarding_details_mapping_id'), table_name='operator_onboarding_details')
    op.drop_index(op.f('ix_operator_onboarding_details_id'), table_name='operator_onboarding_details')
    op.drop_table('operator_onboarding_details')
    op.drop_index(op.f('ix_operator_station_mappings_station_id'), table_name='operator_station_mappings')
    op.drop_index(op.f('ix_operator_station_mappings_operator_id'), table_name='operator_station_mappings')
    op.drop_index(op.f('ix_operator_station_mappings_id'), table_name='operator_station_mappings')
    op.drop_table('operator_station_mappings')
    # ### end Alembic commands ###
