"""add_notifications_last_viewed_at

Revision ID: 791dd5fa60fa
Revises: a410af579e48
Create Date: 2026-07-03 15:18:34.591838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '791dd5fa60fa'
down_revision: Union[str, Sequence[str], None] = 'a410af579e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login_table', sa.Column('notifications_last_viewed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_login_table', 'notifications_last_viewed_at')
    # ### end Alembic commands ###
