"""standardize_master_status

Revision ID: 83259d988978
Revises: 8a994f9be0c6
Create Date: 2026-07-09 15:45:27.193397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83259d988978'
down_revision: Union[str, Sequence[str], None] = '8a994f9be0c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop old foreign keys
    op.drop_constraint(op.f('LMS_table_status_code_fkey'), 'LMS_table', type_='foreignkey')
    op.drop_constraint(op.f('candidate_table_status_code_fkey'), 'candidate_table', type_='foreignkey')
    op.drop_constraint(op.f('dc_remark_table_status_after_code_fkey'), 'dc_remark_table', type_='foreignkey')
    op.drop_constraint(op.f('l1_registration_remark_history_status_after_code_fkey'), 'l1_registration_remark_history', type_='foreignkey')
    op.drop_constraint(op.f('l1_registration_requests_status_code_fkey'), 'l1_registration_requests', type_='foreignkey')
    op.drop_constraint(op.f('l2_registration_remarks_status_after_code_fkey'), 'l2_registration_remarks', type_='foreignkey')
    op.drop_constraint(op.f('l2_registration_requests_status_code_fkey'), 'l2_registration_requests', type_='foreignkey')
    op.drop_constraint(op.f('lms_remark_table_status_after_code_fkey'), 'lms_remark_table', type_='foreignkey')
    op.drop_constraint(op.f('nseit_request_remark_table_status_after_code_fkey'), 'nseit_request_remark_table', type_='foreignkey')
    op.drop_constraint(op.f('nseit_request_table_status_code_fkey'), 'nseit_request_table', type_='foreignkey')
    op.drop_constraint(op.f('operator_activation_remarks_status_after_code_fkey'), 'operator_activation_remarks', type_='foreignkey')
    op.drop_constraint(op.f('operator_activation_requests_status_code_fkey'), 'operator_activation_requests', type_='foreignkey')
    op.drop_constraint(op.f('operator_reactivation_requests_status_code_fkey'), 'operator_reactivation_requests', type_='foreignkey')
    op.drop_constraint(op.f('reactivation_operators_status_code_fkey'), 'reactivation_operators', type_='foreignkey')
    op.drop_constraint(op.f('reactivation_remark_history_status_after_code_fkey'), 'reactivation_remark_history', type_='foreignkey')
    op.drop_constraint(op.f('station_id_remarks_status_after_code_fkey'), 'station_id_remarks', type_='foreignkey')
    op.drop_constraint(op.f('station_id_requests_status_code_fkey'), 'station_id_requests', type_='foreignkey')
    # Drop old indexes
    op.drop_index(op.f('ix_l2_registration_requests_status_code'), table_name='l2_registration_requests')
    op.drop_index(op.f('ix_operator_activation_requests_status_code'), table_name='operator_activation_requests')
    op.drop_index(op.f('ix_operator_reactivation_requests_status_code'), table_name='operator_reactivation_requests')
    op.drop_index(op.f('ix_station_id_requests_status_code'), table_name='station_id_requests')
    # Master Status operations
    op.execute('DELETE FROM master_status')
    op.add_column('master_status', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    op.create_unique_constraint(None, 'master_status', ['name'])
    op.drop_column('master_status', 'code')
    op.create_primary_key('pk_master_status', 'master_status', ['id'])
    op.execute("INSERT INTO master_status (id, name) VALUES (1, 'PENDING')")
    op.execute("INSERT INTO master_status (id, name) VALUES (2, 'APPROVED')")
    op.execute("INSERT INTO master_status (id, name) VALUES (3, 'REVERTED')")
    op.execute("INSERT INTO master_status (id, name) VALUES (4, 'REAPPLIED')")
    op.execute("INSERT INTO master_status (id, name) VALUES (5, 'SENT_TO_CHIPS')")
    op.execute("INSERT INTO master_status (id, name) VALUES (6, 'SENT_TO_UIDAI')")
    op.execute("INSERT INTO master_status (id, name) VALUES (7, 'UIDAI_APPROVED')")
    op.execute("INSERT INTO master_status (id, name) VALUES (8, 'UIDAI_REJECTED')")
    op.execute("INSERT INTO master_status (id, name) VALUES (9, 'REVIEWED')")
    op.execute("INSERT INTO master_status (id, name) VALUES (10, 'ASSIGNED')")
    op.execute("INSERT INTO master_status (id, name) VALUES (11, 'FORWARDED')")
    op.execute("INSERT INTO master_status (id, name) VALUES (12, 'FORWARDED_AGAIN')")
    op.execute("INSERT INTO master_status (id, name) VALUES (13, 'SKIPPED')")
    op.execute("INSERT INTO master_status (id, name) VALUES (14, 'REJECTED')")
    op.execute("INSERT INTO master_status (id, name) VALUES (15, 'REVERTED_BY_CHIPS')")
    op.execute("INSERT INTO master_status (id, name) VALUES (16, 'APPROVED_LEGACY')")
    # Add new columns
    op.add_column('LMS_table', sa.Column('status_id', sa.Integer(), nullable=True))
    op.add_column('candidate_table', sa.Column('status_id', sa.Integer(), nullable=True))
    op.add_column('dc_remark_table', sa.Column('status_after_id', sa.Integer(), nullable=True))
    op.add_column('l1_registration_remark_history', sa.Column('status_after_id', sa.Integer(), nullable=True))
    op.add_column('l1_registration_requests', sa.Column('status_id', sa.Integer(), nullable=True))
    op.add_column('l2_registration_remarks', sa.Column('status_after_id', sa.Integer(), nullable=True))
    op.add_column('l2_registration_requests', sa.Column('status_id', sa.Integer(), nullable=True))
    op.add_column('lms_remark_table', sa.Column('status_after_id', sa.Integer(), nullable=True))
    op.add_column('nseit_request_remark_table', sa.Column('status_after_id', sa.Integer(), nullable=True))
    op.add_column('nseit_request_table', sa.Column('status_id', sa.Integer(), nullable=True))
    op.add_column('operator_activation_remarks', sa.Column('status_after_id', sa.Integer(), nullable=True))
    op.add_column('operator_activation_requests', sa.Column('status_id', sa.Integer(), nullable=True))
    op.add_column('operator_reactivation_requests', sa.Column('status_id', sa.Integer(), nullable=True))
    op.add_column('reactivation_operators', sa.Column('status_id', sa.Integer(), nullable=True))
    op.add_column('reactivation_remark_history', sa.Column('status_after_id', sa.Integer(), nullable=True))
    op.add_column('station_id_remarks', sa.Column('status_after_id', sa.Integer(), nullable=True))
    op.add_column('station_id_requests', sa.Column('status_id', sa.Integer(), nullable=True))
    # Migrate Data
    op.execute("""UPDATE "LMS_table" SET status_id = 1 WHERE status_code = \'PE\'""")
    op.execute("""UPDATE "LMS_table" SET status_id = 2 WHERE status_code = \'AP\'""")
    op.execute("""UPDATE "LMS_table" SET status_id = 3 WHERE status_code = \'RV\'""")
    op.execute("""UPDATE "LMS_table" SET status_id = 4 WHERE status_code = \'RA\'""")
    op.execute("""UPDATE "LMS_table" SET status_id = 5 WHERE status_code = \'SC\'""")
    op.execute("""UPDATE "LMS_table" SET status_id = 6 WHERE status_code = \'SU\'""")
    op.execute("""UPDATE "LMS_table" SET status_id = 7 WHERE status_code = \'UA\'""")
    op.execute("""UPDATE "LMS_table" SET status_id = 8 WHERE status_code = \'UR\'""")
    op.execute("""UPDATE "LMS_table" SET status_id = 9 WHERE status_code = \'RW\'""")
    op.execute("""UPDATE "LMS_table" SET status_id = 10 WHERE status_code = \'AS\'""")
    op.execute("""UPDATE "LMS_table" SET status_id = 11 WHERE status_code = \'FW\'""")
    op.execute("""UPDATE "LMS_table" SET status_id = 12 WHERE status_code = \'FA\'""")
    op.execute("""UPDATE "LMS_table" SET status_id = 13 WHERE status_code = \'SK\'""")
    op.execute("""UPDATE "LMS_table" SET status_id = 14 WHERE status_code = \'RJ\'""")
    op.execute("""UPDATE "LMS_table" SET status_id = 15 WHERE status_code = \'RC\'""")
    op.execute("""UPDATE "LMS_table" SET status_id = 16 WHERE status_code = \'AC\'""")
    op.execute("""UPDATE "candidate_table" SET status_id = 1 WHERE status_code = \'PE\'""")
    op.execute("""UPDATE "candidate_table" SET status_id = 2 WHERE status_code = \'AP\'""")
    op.execute("""UPDATE "candidate_table" SET status_id = 3 WHERE status_code = \'RV\'""")
    op.execute("""UPDATE "candidate_table" SET status_id = 4 WHERE status_code = \'RA\'""")
    op.execute("""UPDATE "candidate_table" SET status_id = 5 WHERE status_code = \'SC\'""")
    op.execute("""UPDATE "candidate_table" SET status_id = 6 WHERE status_code = \'SU\'""")
    op.execute("""UPDATE "candidate_table" SET status_id = 7 WHERE status_code = \'UA\'""")
    op.execute("""UPDATE "candidate_table" SET status_id = 8 WHERE status_code = \'UR\'""")
    op.execute("""UPDATE "candidate_table" SET status_id = 9 WHERE status_code = \'RW\'""")
    op.execute("""UPDATE "candidate_table" SET status_id = 10 WHERE status_code = \'AS\'""")
    op.execute("""UPDATE "candidate_table" SET status_id = 11 WHERE status_code = \'FW\'""")
    op.execute("""UPDATE "candidate_table" SET status_id = 12 WHERE status_code = \'FA\'""")
    op.execute("""UPDATE "candidate_table" SET status_id = 13 WHERE status_code = \'SK\'""")
    op.execute("""UPDATE "candidate_table" SET status_id = 14 WHERE status_code = \'RJ\'""")
    op.execute("""UPDATE "candidate_table" SET status_id = 15 WHERE status_code = \'RC\'""")
    op.execute("""UPDATE "candidate_table" SET status_id = 16 WHERE status_code = \'AC\'""")
    op.execute("""UPDATE "dc_remark_table" SET status_after_id = 1 WHERE status_after_code = \'PE\'""")
    op.execute("""UPDATE "dc_remark_table" SET status_after_id = 2 WHERE status_after_code = \'AP\'""")
    op.execute("""UPDATE "dc_remark_table" SET status_after_id = 3 WHERE status_after_code = \'RV\'""")
    op.execute("""UPDATE "dc_remark_table" SET status_after_id = 4 WHERE status_after_code = \'RA\'""")
    op.execute("""UPDATE "dc_remark_table" SET status_after_id = 5 WHERE status_after_code = \'SC\'""")
    op.execute("""UPDATE "dc_remark_table" SET status_after_id = 6 WHERE status_after_code = \'SU\'""")
    op.execute("""UPDATE "dc_remark_table" SET status_after_id = 7 WHERE status_after_code = \'UA\'""")
    op.execute("""UPDATE "dc_remark_table" SET status_after_id = 8 WHERE status_after_code = \'UR\'""")
    op.execute("""UPDATE "dc_remark_table" SET status_after_id = 9 WHERE status_after_code = \'RW\'""")
    op.execute("""UPDATE "dc_remark_table" SET status_after_id = 10 WHERE status_after_code = \'AS\'""")
    op.execute("""UPDATE "dc_remark_table" SET status_after_id = 11 WHERE status_after_code = \'FW\'""")
    op.execute("""UPDATE "dc_remark_table" SET status_after_id = 12 WHERE status_after_code = \'FA\'""")
    op.execute("""UPDATE "dc_remark_table" SET status_after_id = 13 WHERE status_after_code = \'SK\'""")
    op.execute("""UPDATE "dc_remark_table" SET status_after_id = 14 WHERE status_after_code = \'RJ\'""")
    op.execute("""UPDATE "dc_remark_table" SET status_after_id = 15 WHERE status_after_code = \'RC\'""")
    op.execute("""UPDATE "dc_remark_table" SET status_after_id = 16 WHERE status_after_code = \'AC\'""")
    op.execute("""UPDATE "l1_registration_remark_history" SET status_after_id = 1 WHERE status_after_code = \'PE\'""")
    op.execute("""UPDATE "l1_registration_remark_history" SET status_after_id = 2 WHERE status_after_code = \'AP\'""")
    op.execute("""UPDATE "l1_registration_remark_history" SET status_after_id = 3 WHERE status_after_code = \'RV\'""")
    op.execute("""UPDATE "l1_registration_remark_history" SET status_after_id = 4 WHERE status_after_code = \'RA\'""")
    op.execute("""UPDATE "l1_registration_remark_history" SET status_after_id = 5 WHERE status_after_code = \'SC\'""")
    op.execute("""UPDATE "l1_registration_remark_history" SET status_after_id = 6 WHERE status_after_code = \'SU\'""")
    op.execute("""UPDATE "l1_registration_remark_history" SET status_after_id = 7 WHERE status_after_code = \'UA\'""")
    op.execute("""UPDATE "l1_registration_remark_history" SET status_after_id = 8 WHERE status_after_code = \'UR\'""")
    op.execute("""UPDATE "l1_registration_remark_history" SET status_after_id = 9 WHERE status_after_code = \'RW\'""")
    op.execute("""UPDATE "l1_registration_remark_history" SET status_after_id = 10 WHERE status_after_code = \'AS\'""")
    op.execute("""UPDATE "l1_registration_remark_history" SET status_after_id = 11 WHERE status_after_code = \'FW\'""")
    op.execute("""UPDATE "l1_registration_remark_history" SET status_after_id = 12 WHERE status_after_code = \'FA\'""")
    op.execute("""UPDATE "l1_registration_remark_history" SET status_after_id = 13 WHERE status_after_code = \'SK\'""")
    op.execute("""UPDATE "l1_registration_remark_history" SET status_after_id = 14 WHERE status_after_code = \'RJ\'""")
    op.execute("""UPDATE "l1_registration_remark_history" SET status_after_id = 15 WHERE status_after_code = \'RC\'""")
    op.execute("""UPDATE "l1_registration_remark_history" SET status_after_id = 16 WHERE status_after_code = \'AC\'""")
    op.execute("""UPDATE "l1_registration_requests" SET status_id = 1 WHERE status_code = \'PE\'""")
    op.execute("""UPDATE "l1_registration_requests" SET status_id = 2 WHERE status_code = \'AP\'""")
    op.execute("""UPDATE "l1_registration_requests" SET status_id = 3 WHERE status_code = \'RV\'""")
    op.execute("""UPDATE "l1_registration_requests" SET status_id = 4 WHERE status_code = \'RA\'""")
    op.execute("""UPDATE "l1_registration_requests" SET status_id = 5 WHERE status_code = \'SC\'""")
    op.execute("""UPDATE "l1_registration_requests" SET status_id = 6 WHERE status_code = \'SU\'""")
    op.execute("""UPDATE "l1_registration_requests" SET status_id = 7 WHERE status_code = \'UA\'""")
    op.execute("""UPDATE "l1_registration_requests" SET status_id = 8 WHERE status_code = \'UR\'""")
    op.execute("""UPDATE "l1_registration_requests" SET status_id = 9 WHERE status_code = \'RW\'""")
    op.execute("""UPDATE "l1_registration_requests" SET status_id = 10 WHERE status_code = \'AS\'""")
    op.execute("""UPDATE "l1_registration_requests" SET status_id = 11 WHERE status_code = \'FW\'""")
    op.execute("""UPDATE "l1_registration_requests" SET status_id = 12 WHERE status_code = \'FA\'""")
    op.execute("""UPDATE "l1_registration_requests" SET status_id = 13 WHERE status_code = \'SK\'""")
    op.execute("""UPDATE "l1_registration_requests" SET status_id = 14 WHERE status_code = \'RJ\'""")
    op.execute("""UPDATE "l1_registration_requests" SET status_id = 15 WHERE status_code = \'RC\'""")
    op.execute("""UPDATE "l1_registration_requests" SET status_id = 16 WHERE status_code = \'AC\'""")
    op.execute("""UPDATE "l2_registration_remarks" SET status_after_id = 1 WHERE status_after_code = \'PE\'""")
    op.execute("""UPDATE "l2_registration_remarks" SET status_after_id = 2 WHERE status_after_code = \'AP\'""")
    op.execute("""UPDATE "l2_registration_remarks" SET status_after_id = 3 WHERE status_after_code = \'RV\'""")
    op.execute("""UPDATE "l2_registration_remarks" SET status_after_id = 4 WHERE status_after_code = \'RA\'""")
    op.execute("""UPDATE "l2_registration_remarks" SET status_after_id = 5 WHERE status_after_code = \'SC\'""")
    op.execute("""UPDATE "l2_registration_remarks" SET status_after_id = 6 WHERE status_after_code = \'SU\'""")
    op.execute("""UPDATE "l2_registration_remarks" SET status_after_id = 7 WHERE status_after_code = \'UA\'""")
    op.execute("""UPDATE "l2_registration_remarks" SET status_after_id = 8 WHERE status_after_code = \'UR\'""")
    op.execute("""UPDATE "l2_registration_remarks" SET status_after_id = 9 WHERE status_after_code = \'RW\'""")
    op.execute("""UPDATE "l2_registration_remarks" SET status_after_id = 10 WHERE status_after_code = \'AS\'""")
    op.execute("""UPDATE "l2_registration_remarks" SET status_after_id = 11 WHERE status_after_code = \'FW\'""")
    op.execute("""UPDATE "l2_registration_remarks" SET status_after_id = 12 WHERE status_after_code = \'FA\'""")
    op.execute("""UPDATE "l2_registration_remarks" SET status_after_id = 13 WHERE status_after_code = \'SK\'""")
    op.execute("""UPDATE "l2_registration_remarks" SET status_after_id = 14 WHERE status_after_code = \'RJ\'""")
    op.execute("""UPDATE "l2_registration_remarks" SET status_after_id = 15 WHERE status_after_code = \'RC\'""")
    op.execute("""UPDATE "l2_registration_remarks" SET status_after_id = 16 WHERE status_after_code = \'AC\'""")
    op.execute("""UPDATE "l2_registration_requests" SET status_id = 1 WHERE status_code = \'PE\'""")
    op.execute("""UPDATE "l2_registration_requests" SET status_id = 2 WHERE status_code = \'AP\'""")
    op.execute("""UPDATE "l2_registration_requests" SET status_id = 3 WHERE status_code = \'RV\'""")
    op.execute("""UPDATE "l2_registration_requests" SET status_id = 4 WHERE status_code = \'RA\'""")
    op.execute("""UPDATE "l2_registration_requests" SET status_id = 5 WHERE status_code = \'SC\'""")
    op.execute("""UPDATE "l2_registration_requests" SET status_id = 6 WHERE status_code = \'SU\'""")
    op.execute("""UPDATE "l2_registration_requests" SET status_id = 7 WHERE status_code = \'UA\'""")
    op.execute("""UPDATE "l2_registration_requests" SET status_id = 8 WHERE status_code = \'UR\'""")
    op.execute("""UPDATE "l2_registration_requests" SET status_id = 9 WHERE status_code = \'RW\'""")
    op.execute("""UPDATE "l2_registration_requests" SET status_id = 10 WHERE status_code = \'AS\'""")
    op.execute("""UPDATE "l2_registration_requests" SET status_id = 11 WHERE status_code = \'FW\'""")
    op.execute("""UPDATE "l2_registration_requests" SET status_id = 12 WHERE status_code = \'FA\'""")
    op.execute("""UPDATE "l2_registration_requests" SET status_id = 13 WHERE status_code = \'SK\'""")
    op.execute("""UPDATE "l2_registration_requests" SET status_id = 14 WHERE status_code = \'RJ\'""")
    op.execute("""UPDATE "l2_registration_requests" SET status_id = 15 WHERE status_code = \'RC\'""")
    op.execute("""UPDATE "l2_registration_requests" SET status_id = 16 WHERE status_code = \'AC\'""")
    op.execute("""UPDATE "lms_remark_table" SET status_after_id = 1 WHERE status_after_code = \'PE\'""")
    op.execute("""UPDATE "lms_remark_table" SET status_after_id = 2 WHERE status_after_code = \'AP\'""")
    op.execute("""UPDATE "lms_remark_table" SET status_after_id = 3 WHERE status_after_code = \'RV\'""")
    op.execute("""UPDATE "lms_remark_table" SET status_after_id = 4 WHERE status_after_code = \'RA\'""")
    op.execute("""UPDATE "lms_remark_table" SET status_after_id = 5 WHERE status_after_code = \'SC\'""")
    op.execute("""UPDATE "lms_remark_table" SET status_after_id = 6 WHERE status_after_code = \'SU\'""")
    op.execute("""UPDATE "lms_remark_table" SET status_after_id = 7 WHERE status_after_code = \'UA\'""")
    op.execute("""UPDATE "lms_remark_table" SET status_after_id = 8 WHERE status_after_code = \'UR\'""")
    op.execute("""UPDATE "lms_remark_table" SET status_after_id = 9 WHERE status_after_code = \'RW\'""")
    op.execute("""UPDATE "lms_remark_table" SET status_after_id = 10 WHERE status_after_code = \'AS\'""")
    op.execute("""UPDATE "lms_remark_table" SET status_after_id = 11 WHERE status_after_code = \'FW\'""")
    op.execute("""UPDATE "lms_remark_table" SET status_after_id = 12 WHERE status_after_code = \'FA\'""")
    op.execute("""UPDATE "lms_remark_table" SET status_after_id = 13 WHERE status_after_code = \'SK\'""")
    op.execute("""UPDATE "lms_remark_table" SET status_after_id = 14 WHERE status_after_code = \'RJ\'""")
    op.execute("""UPDATE "lms_remark_table" SET status_after_id = 15 WHERE status_after_code = \'RC\'""")
    op.execute("""UPDATE "lms_remark_table" SET status_after_id = 16 WHERE status_after_code = \'AC\'""")
    op.execute("""UPDATE "nseit_request_remark_table" SET status_after_id = 1 WHERE status_after_code = \'PE\'""")
    op.execute("""UPDATE "nseit_request_remark_table" SET status_after_id = 2 WHERE status_after_code = \'AP\'""")
    op.execute("""UPDATE "nseit_request_remark_table" SET status_after_id = 3 WHERE status_after_code = \'RV\'""")
    op.execute("""UPDATE "nseit_request_remark_table" SET status_after_id = 4 WHERE status_after_code = \'RA\'""")
    op.execute("""UPDATE "nseit_request_remark_table" SET status_after_id = 5 WHERE status_after_code = \'SC\'""")
    op.execute("""UPDATE "nseit_request_remark_table" SET status_after_id = 6 WHERE status_after_code = \'SU\'""")
    op.execute("""UPDATE "nseit_request_remark_table" SET status_after_id = 7 WHERE status_after_code = \'UA\'""")
    op.execute("""UPDATE "nseit_request_remark_table" SET status_after_id = 8 WHERE status_after_code = \'UR\'""")
    op.execute("""UPDATE "nseit_request_remark_table" SET status_after_id = 9 WHERE status_after_code = \'RW\'""")
    op.execute("""UPDATE "nseit_request_remark_table" SET status_after_id = 10 WHERE status_after_code = \'AS\'""")
    op.execute("""UPDATE "nseit_request_remark_table" SET status_after_id = 11 WHERE status_after_code = \'FW\'""")
    op.execute("""UPDATE "nseit_request_remark_table" SET status_after_id = 12 WHERE status_after_code = \'FA\'""")
    op.execute("""UPDATE "nseit_request_remark_table" SET status_after_id = 13 WHERE status_after_code = \'SK\'""")
    op.execute("""UPDATE "nseit_request_remark_table" SET status_after_id = 14 WHERE status_after_code = \'RJ\'""")
    op.execute("""UPDATE "nseit_request_remark_table" SET status_after_id = 15 WHERE status_after_code = \'RC\'""")
    op.execute("""UPDATE "nseit_request_remark_table" SET status_after_id = 16 WHERE status_after_code = \'AC\'""")
    op.execute("""UPDATE "nseit_request_table" SET status_id = 1 WHERE status_code = \'PE\'""")
    op.execute("""UPDATE "nseit_request_table" SET status_id = 2 WHERE status_code = \'AP\'""")
    op.execute("""UPDATE "nseit_request_table" SET status_id = 3 WHERE status_code = \'RV\'""")
    op.execute("""UPDATE "nseit_request_table" SET status_id = 4 WHERE status_code = \'RA\'""")
    op.execute("""UPDATE "nseit_request_table" SET status_id = 5 WHERE status_code = \'SC\'""")
    op.execute("""UPDATE "nseit_request_table" SET status_id = 6 WHERE status_code = \'SU\'""")
    op.execute("""UPDATE "nseit_request_table" SET status_id = 7 WHERE status_code = \'UA\'""")
    op.execute("""UPDATE "nseit_request_table" SET status_id = 8 WHERE status_code = \'UR\'""")
    op.execute("""UPDATE "nseit_request_table" SET status_id = 9 WHERE status_code = \'RW\'""")
    op.execute("""UPDATE "nseit_request_table" SET status_id = 10 WHERE status_code = \'AS\'""")
    op.execute("""UPDATE "nseit_request_table" SET status_id = 11 WHERE status_code = \'FW\'""")
    op.execute("""UPDATE "nseit_request_table" SET status_id = 12 WHERE status_code = \'FA\'""")
    op.execute("""UPDATE "nseit_request_table" SET status_id = 13 WHERE status_code = \'SK\'""")
    op.execute("""UPDATE "nseit_request_table" SET status_id = 14 WHERE status_code = \'RJ\'""")
    op.execute("""UPDATE "nseit_request_table" SET status_id = 15 WHERE status_code = \'RC\'""")
    op.execute("""UPDATE "nseit_request_table" SET status_id = 16 WHERE status_code = \'AC\'""")
    op.execute("""UPDATE "operator_activation_remarks" SET status_after_id = 1 WHERE status_after_code = \'PE\'""")
    op.execute("""UPDATE "operator_activation_remarks" SET status_after_id = 2 WHERE status_after_code = \'AP\'""")
    op.execute("""UPDATE "operator_activation_remarks" SET status_after_id = 3 WHERE status_after_code = \'RV\'""")
    op.execute("""UPDATE "operator_activation_remarks" SET status_after_id = 4 WHERE status_after_code = \'RA\'""")
    op.execute("""UPDATE "operator_activation_remarks" SET status_after_id = 5 WHERE status_after_code = \'SC\'""")
    op.execute("""UPDATE "operator_activation_remarks" SET status_after_id = 6 WHERE status_after_code = \'SU\'""")
    op.execute("""UPDATE "operator_activation_remarks" SET status_after_id = 7 WHERE status_after_code = \'UA\'""")
    op.execute("""UPDATE "operator_activation_remarks" SET status_after_id = 8 WHERE status_after_code = \'UR\'""")
    op.execute("""UPDATE "operator_activation_remarks" SET status_after_id = 9 WHERE status_after_code = \'RW\'""")
    op.execute("""UPDATE "operator_activation_remarks" SET status_after_id = 10 WHERE status_after_code = \'AS\'""")
    op.execute("""UPDATE "operator_activation_remarks" SET status_after_id = 11 WHERE status_after_code = \'FW\'""")
    op.execute("""UPDATE "operator_activation_remarks" SET status_after_id = 12 WHERE status_after_code = \'FA\'""")
    op.execute("""UPDATE "operator_activation_remarks" SET status_after_id = 13 WHERE status_after_code = \'SK\'""")
    op.execute("""UPDATE "operator_activation_remarks" SET status_after_id = 14 WHERE status_after_code = \'RJ\'""")
    op.execute("""UPDATE "operator_activation_remarks" SET status_after_id = 15 WHERE status_after_code = \'RC\'""")
    op.execute("""UPDATE "operator_activation_remarks" SET status_after_id = 16 WHERE status_after_code = \'AC\'""")
    op.execute("""UPDATE "operator_activation_requests" SET status_id = 1 WHERE status_code = \'PE\'""")
    op.execute("""UPDATE "operator_activation_requests" SET status_id = 2 WHERE status_code = \'AP\'""")
    op.execute("""UPDATE "operator_activation_requests" SET status_id = 3 WHERE status_code = \'RV\'""")
    op.execute("""UPDATE "operator_activation_requests" SET status_id = 4 WHERE status_code = \'RA\'""")
    op.execute("""UPDATE "operator_activation_requests" SET status_id = 5 WHERE status_code = \'SC\'""")
    op.execute("""UPDATE "operator_activation_requests" SET status_id = 6 WHERE status_code = \'SU\'""")
    op.execute("""UPDATE "operator_activation_requests" SET status_id = 7 WHERE status_code = \'UA\'""")
    op.execute("""UPDATE "operator_activation_requests" SET status_id = 8 WHERE status_code = \'UR\'""")
    op.execute("""UPDATE "operator_activation_requests" SET status_id = 9 WHERE status_code = \'RW\'""")
    op.execute("""UPDATE "operator_activation_requests" SET status_id = 10 WHERE status_code = \'AS\'""")
    op.execute("""UPDATE "operator_activation_requests" SET status_id = 11 WHERE status_code = \'FW\'""")
    op.execute("""UPDATE "operator_activation_requests" SET status_id = 12 WHERE status_code = \'FA\'""")
    op.execute("""UPDATE "operator_activation_requests" SET status_id = 13 WHERE status_code = \'SK\'""")
    op.execute("""UPDATE "operator_activation_requests" SET status_id = 14 WHERE status_code = \'RJ\'""")
    op.execute("""UPDATE "operator_activation_requests" SET status_id = 15 WHERE status_code = \'RC\'""")
    op.execute("""UPDATE "operator_activation_requests" SET status_id = 16 WHERE status_code = \'AC\'""")
    op.execute("""UPDATE "operator_reactivation_requests" SET status_id = 1 WHERE status_code = \'PE\'""")
    op.execute("""UPDATE "operator_reactivation_requests" SET status_id = 2 WHERE status_code = \'AP\'""")
    op.execute("""UPDATE "operator_reactivation_requests" SET status_id = 3 WHERE status_code = \'RV\'""")
    op.execute("""UPDATE "operator_reactivation_requests" SET status_id = 4 WHERE status_code = \'RA\'""")
    op.execute("""UPDATE "operator_reactivation_requests" SET status_id = 5 WHERE status_code = \'SC\'""")
    op.execute("""UPDATE "operator_reactivation_requests" SET status_id = 6 WHERE status_code = \'SU\'""")
    op.execute("""UPDATE "operator_reactivation_requests" SET status_id = 7 WHERE status_code = \'UA\'""")
    op.execute("""UPDATE "operator_reactivation_requests" SET status_id = 8 WHERE status_code = \'UR\'""")
    op.execute("""UPDATE "operator_reactivation_requests" SET status_id = 9 WHERE status_code = \'RW\'""")
    op.execute("""UPDATE "operator_reactivation_requests" SET status_id = 10 WHERE status_code = \'AS\'""")
    op.execute("""UPDATE "operator_reactivation_requests" SET status_id = 11 WHERE status_code = \'FW\'""")
    op.execute("""UPDATE "operator_reactivation_requests" SET status_id = 12 WHERE status_code = \'FA\'""")
    op.execute("""UPDATE "operator_reactivation_requests" SET status_id = 13 WHERE status_code = \'SK\'""")
    op.execute("""UPDATE "operator_reactivation_requests" SET status_id = 14 WHERE status_code = \'RJ\'""")
    op.execute("""UPDATE "operator_reactivation_requests" SET status_id = 15 WHERE status_code = \'RC\'""")
    op.execute("""UPDATE "operator_reactivation_requests" SET status_id = 16 WHERE status_code = \'AC\'""")
    op.execute("""UPDATE "reactivation_operators" SET status_id = 1 WHERE status_code = \'PE\'""")
    op.execute("""UPDATE "reactivation_operators" SET status_id = 2 WHERE status_code = \'AP\'""")
    op.execute("""UPDATE "reactivation_operators" SET status_id = 3 WHERE status_code = \'RV\'""")
    op.execute("""UPDATE "reactivation_operators" SET status_id = 4 WHERE status_code = \'RA\'""")
    op.execute("""UPDATE "reactivation_operators" SET status_id = 5 WHERE status_code = \'SC\'""")
    op.execute("""UPDATE "reactivation_operators" SET status_id = 6 WHERE status_code = \'SU\'""")
    op.execute("""UPDATE "reactivation_operators" SET status_id = 7 WHERE status_code = \'UA\'""")
    op.execute("""UPDATE "reactivation_operators" SET status_id = 8 WHERE status_code = \'UR\'""")
    op.execute("""UPDATE "reactivation_operators" SET status_id = 9 WHERE status_code = \'RW\'""")
    op.execute("""UPDATE "reactivation_operators" SET status_id = 10 WHERE status_code = \'AS\'""")
    op.execute("""UPDATE "reactivation_operators" SET status_id = 11 WHERE status_code = \'FW\'""")
    op.execute("""UPDATE "reactivation_operators" SET status_id = 12 WHERE status_code = \'FA\'""")
    op.execute("""UPDATE "reactivation_operators" SET status_id = 13 WHERE status_code = \'SK\'""")
    op.execute("""UPDATE "reactivation_operators" SET status_id = 14 WHERE status_code = \'RJ\'""")
    op.execute("""UPDATE "reactivation_operators" SET status_id = 15 WHERE status_code = \'RC\'""")
    op.execute("""UPDATE "reactivation_operators" SET status_id = 16 WHERE status_code = \'AC\'""")
    op.execute("""UPDATE "reactivation_remark_history" SET status_after_id = 1 WHERE status_after_code = \'PE\'""")
    op.execute("""UPDATE "reactivation_remark_history" SET status_after_id = 2 WHERE status_after_code = \'AP\'""")
    op.execute("""UPDATE "reactivation_remark_history" SET status_after_id = 3 WHERE status_after_code = \'RV\'""")
    op.execute("""UPDATE "reactivation_remark_history" SET status_after_id = 4 WHERE status_after_code = \'RA\'""")
    op.execute("""UPDATE "reactivation_remark_history" SET status_after_id = 5 WHERE status_after_code = \'SC\'""")
    op.execute("""UPDATE "reactivation_remark_history" SET status_after_id = 6 WHERE status_after_code = \'SU\'""")
    op.execute("""UPDATE "reactivation_remark_history" SET status_after_id = 7 WHERE status_after_code = \'UA\'""")
    op.execute("""UPDATE "reactivation_remark_history" SET status_after_id = 8 WHERE status_after_code = \'UR\'""")
    op.execute("""UPDATE "reactivation_remark_history" SET status_after_id = 9 WHERE status_after_code = \'RW\'""")
    op.execute("""UPDATE "reactivation_remark_history" SET status_after_id = 10 WHERE status_after_code = \'AS\'""")
    op.execute("""UPDATE "reactivation_remark_history" SET status_after_id = 11 WHERE status_after_code = \'FW\'""")
    op.execute("""UPDATE "reactivation_remark_history" SET status_after_id = 12 WHERE status_after_code = \'FA\'""")
    op.execute("""UPDATE "reactivation_remark_history" SET status_after_id = 13 WHERE status_after_code = \'SK\'""")
    op.execute("""UPDATE "reactivation_remark_history" SET status_after_id = 14 WHERE status_after_code = \'RJ\'""")
    op.execute("""UPDATE "reactivation_remark_history" SET status_after_id = 15 WHERE status_after_code = \'RC\'""")
    op.execute("""UPDATE "reactivation_remark_history" SET status_after_id = 16 WHERE status_after_code = \'AC\'""")
    op.execute("""UPDATE "station_id_remarks" SET status_after_id = 1 WHERE status_after_code = \'PE\'""")
    op.execute("""UPDATE "station_id_remarks" SET status_after_id = 2 WHERE status_after_code = \'AP\'""")
    op.execute("""UPDATE "station_id_remarks" SET status_after_id = 3 WHERE status_after_code = \'RV\'""")
    op.execute("""UPDATE "station_id_remarks" SET status_after_id = 4 WHERE status_after_code = \'RA\'""")
    op.execute("""UPDATE "station_id_remarks" SET status_after_id = 5 WHERE status_after_code = \'SC\'""")
    op.execute("""UPDATE "station_id_remarks" SET status_after_id = 6 WHERE status_after_code = \'SU\'""")
    op.execute("""UPDATE "station_id_remarks" SET status_after_id = 7 WHERE status_after_code = \'UA\'""")
    op.execute("""UPDATE "station_id_remarks" SET status_after_id = 8 WHERE status_after_code = \'UR\'""")
    op.execute("""UPDATE "station_id_remarks" SET status_after_id = 9 WHERE status_after_code = \'RW\'""")
    op.execute("""UPDATE "station_id_remarks" SET status_after_id = 10 WHERE status_after_code = \'AS\'""")
    op.execute("""UPDATE "station_id_remarks" SET status_after_id = 11 WHERE status_after_code = \'FW\'""")
    op.execute("""UPDATE "station_id_remarks" SET status_after_id = 12 WHERE status_after_code = \'FA\'""")
    op.execute("""UPDATE "station_id_remarks" SET status_after_id = 13 WHERE status_after_code = \'SK\'""")
    op.execute("""UPDATE "station_id_remarks" SET status_after_id = 14 WHERE status_after_code = \'RJ\'""")
    op.execute("""UPDATE "station_id_remarks" SET status_after_id = 15 WHERE status_after_code = \'RC\'""")
    op.execute("""UPDATE "station_id_remarks" SET status_after_id = 16 WHERE status_after_code = \'AC\'""")
    op.execute("""UPDATE "station_id_requests" SET status_id = 1 WHERE status_code = \'PE\'""")
    op.execute("""UPDATE "station_id_requests" SET status_id = 2 WHERE status_code = \'AP\'""")
    op.execute("""UPDATE "station_id_requests" SET status_id = 3 WHERE status_code = \'RV\'""")
    op.execute("""UPDATE "station_id_requests" SET status_id = 4 WHERE status_code = \'RA\'""")
    op.execute("""UPDATE "station_id_requests" SET status_id = 5 WHERE status_code = \'SC\'""")
    op.execute("""UPDATE "station_id_requests" SET status_id = 6 WHERE status_code = \'SU\'""")
    op.execute("""UPDATE "station_id_requests" SET status_id = 7 WHERE status_code = \'UA\'""")
    op.execute("""UPDATE "station_id_requests" SET status_id = 8 WHERE status_code = \'UR\'""")
    op.execute("""UPDATE "station_id_requests" SET status_id = 9 WHERE status_code = \'RW\'""")
    op.execute("""UPDATE "station_id_requests" SET status_id = 10 WHERE status_code = \'AS\'""")
    op.execute("""UPDATE "station_id_requests" SET status_id = 11 WHERE status_code = \'FW\'""")
    op.execute("""UPDATE "station_id_requests" SET status_id = 12 WHERE status_code = \'FA\'""")
    op.execute("""UPDATE "station_id_requests" SET status_id = 13 WHERE status_code = \'SK\'""")
    op.execute("""UPDATE "station_id_requests" SET status_id = 14 WHERE status_code = \'RJ\'""")
    op.execute("""UPDATE "station_id_requests" SET status_id = 15 WHERE status_code = \'RC\'""")
    op.execute("""UPDATE "station_id_requests" SET status_id = 16 WHERE status_code = \'AC\'""")
    # Drop old columns
    op.drop_column('LMS_table', 'status_code')
    op.drop_column('candidate_table', 'status_code')
    op.drop_column('dc_remark_table', 'status_after_code')
    op.drop_column('l1_registration_remark_history', 'status_after_code')
    op.drop_column('l1_registration_requests', 'status_code')
    op.drop_column('l2_registration_remarks', 'status_after_code')
    op.drop_column('l2_registration_requests', 'status_code')
    op.drop_column('lms_remark_table', 'status_after_code')
    op.drop_column('nseit_request_remark_table', 'status_after_code')
    op.drop_column('nseit_request_table', 'status_code')
    op.drop_column('operator_activation_remarks', 'status_after_code')
    op.drop_column('operator_activation_requests', 'status_code')
    op.drop_column('operator_reactivation_requests', 'status_code')
    op.drop_column('reactivation_operators', 'status_code')
    op.drop_column('reactivation_remark_history', 'status_after_code')
    op.drop_column('station_id_remarks', 'status_after_code')
    op.drop_column('station_id_requests', 'status_code')
    # Create new foreign keys and indexes
    op.create_foreign_key(None, 'LMS_table', 'master_status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'candidate_table', 'master_status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'dc_remark_table', 'master_status', ['status_after_id'], ['id'])
    op.create_foreign_key(None, 'l1_registration_remark_history', 'master_status', ['status_after_id'], ['id'])
    op.create_foreign_key(None, 'l1_registration_requests', 'master_status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'l2_registration_remarks', 'master_status', ['status_after_id'], ['id'])
    op.create_index(op.f('ix_l2_registration_requests_status_id'), 'l2_registration_requests', ['status_id'], unique=False)
    op.create_foreign_key(None, 'l2_registration_requests', 'master_status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'lms_remark_table', 'master_status', ['status_after_id'], ['id'])
    op.create_foreign_key(None, 'nseit_request_remark_table', 'master_status', ['status_after_id'], ['id'])
    op.create_foreign_key(None, 'nseit_request_table', 'master_status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'operator_activation_remarks', 'master_status', ['status_after_id'], ['id'])
    op.create_index(op.f('ix_operator_activation_requests_status_id'), 'operator_activation_requests', ['status_id'], unique=False)
    op.create_foreign_key(None, 'operator_activation_requests', 'master_status', ['status_id'], ['id'])
    op.create_index(op.f('ix_operator_reactivation_requests_status_id'), 'operator_reactivation_requests', ['status_id'], unique=False)
    op.create_foreign_key(None, 'operator_reactivation_requests', 'master_status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'reactivation_operators', 'master_status', ['status_id'], ['id'])
    op.create_foreign_key(None, 'reactivation_remark_history', 'master_status', ['status_after_id'], ['id'])
    op.create_foreign_key(None, 'station_id_remarks', 'master_status', ['status_after_id'], ['id'])
    op.create_index(op.f('ix_station_id_requests_status_id'), 'station_id_requests', ['status_id'], unique=False)
    op.create_foreign_key(None, 'station_id_requests', 'master_status', ['status_id'], ['id'])

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('station_id_requests', sa.Column('status_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'station_id_requests', type_='foreignkey')
    op.create_foreign_key(op.f('station_id_requests_status_code_fkey'), 'station_id_requests', 'master_status', ['status_code'], ['code'])
    op.drop_index(op.f('ix_station_id_requests_status_id'), table_name='station_id_requests')
    op.create_index(op.f('ix_station_id_requests_status_code'), 'station_id_requests', ['status_code'], unique=False)
    op.drop_column('station_id_requests', 'status_id')
    op.add_column('station_id_remarks', sa.Column('status_after_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'station_id_remarks', type_='foreignkey')
    op.create_foreign_key(op.f('station_id_remarks_status_after_code_fkey'), 'station_id_remarks', 'master_status', ['status_after_code'], ['code'])
    op.drop_column('station_id_remarks', 'status_after_id')
    op.add_column('reactivation_remark_history', sa.Column('status_after_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reactivation_remark_history', type_='foreignkey')
    op.create_foreign_key(op.f('reactivation_remark_history_status_after_code_fkey'), 'reactivation_remark_history', 'master_status', ['status_after_code'], ['code'])
    op.drop_column('reactivation_remark_history', 'status_after_id')
    op.add_column('reactivation_operators', sa.Column('status_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reactivation_operators', type_='foreignkey')
    op.create_foreign_key(op.f('reactivation_operators_status_code_fkey'), 'reactivation_operators', 'master_status', ['status_code'], ['code'])
    op.drop_column('reactivation_operators', 'status_id')
    op.add_column('operator_reactivation_requests', sa.Column('status_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'operator_reactivation_requests', type_='foreignkey')
    op.create_foreign_key(op.f('operator_reactivation_requests_status_code_fkey'), 'operator_reactivation_requests', 'master_status', ['status_code'], ['code'])
    op.drop_index(op.f('ix_operator_reactivation_requests_status_id'), table_name='operator_reactivation_requests')
    op.create_index(op.f('ix_operator_reactivation_requests_status_code'), 'operator_reactivation_requests', ['status_code'], unique=False)
    op.drop_column('operator_reactivation_requests', 'status_id')
    op.add_column('operator_activation_requests', sa.Column('status_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'operator_activation_requests', type_='foreignkey')
    op.create_foreign_key(op.f('operator_activation_requests_status_code_fkey'), 'operator_activation_requests', 'master_status', ['status_code'], ['code'])
    op.drop_index(op.f('ix_operator_activation_requests_status_id'), table_name='operator_activation_requests')
    op.create_index(op.f('ix_operator_activation_requests_status_code'), 'operator_activation_requests', ['status_code'], unique=False)
    op.drop_column('operator_activation_requests', 'status_id')
    op.add_column('operator_activation_remarks', sa.Column('status_after_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'operator_activation_remarks', type_='foreignkey')
    op.create_foreign_key(op.f('operator_activation_remarks_status_after_code_fkey'), 'operator_activation_remarks', 'master_status', ['status_after_code'], ['code'])
    op.drop_column('operator_activation_remarks', 'status_after_id')
    op.add_column('nseit_request_table', sa.Column('status_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'nseit_request_table', type_='foreignkey')
    op.create_foreign_key(op.f('nseit_request_table_status_code_fkey'), 'nseit_request_table', 'master_status', ['status_code'], ['code'])
    op.drop_column('nseit_request_table', 'status_id')
    op.add_column('nseit_request_remark_table', sa.Column('status_after_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'nseit_request_remark_table', type_='foreignkey')
    op.create_foreign_key(op.f('nseit_request_remark_table_status_after_code_fkey'), 'nseit_request_remark_table', 'master_status', ['status_after_code'], ['code'])
    op.drop_column('nseit_request_remark_table', 'status_after_id')
    op.add_column('master_status', sa.Column('code', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'master_status', type_='unique')
    op.drop_column('master_status', 'id')
    op.add_column('lms_remark_table', sa.Column('status_after_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lms_remark_table', type_='foreignkey')
    op.create_foreign_key(op.f('lms_remark_table_status_after_code_fkey'), 'lms_remark_table', 'master_status', ['status_after_code'], ['code'])
    op.drop_column('lms_remark_table', 'status_after_id')
    op.add_column('l2_registration_requests', sa.Column('status_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'l2_registration_requests', type_='foreignkey')
    op.create_foreign_key(op.f('l2_registration_requests_status_code_fkey'), 'l2_registration_requests', 'master_status', ['status_code'], ['code'])
    op.drop_index(op.f('ix_l2_registration_requests_status_id'), table_name='l2_registration_requests')
    op.create_index(op.f('ix_l2_registration_requests_status_code'), 'l2_registration_requests', ['status_code'], unique=False)
    op.drop_column('l2_registration_requests', 'status_id')
    op.add_column('l2_registration_remarks', sa.Column('status_after_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'l2_registration_remarks', type_='foreignkey')
    op.create_foreign_key(op.f('l2_registration_remarks_status_after_code_fkey'), 'l2_registration_remarks', 'master_status', ['status_after_code'], ['code'])
    op.drop_column('l2_registration_remarks', 'status_after_id')
    op.add_column('l1_registration_requests', sa.Column('status_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'l1_registration_requests', type_='foreignkey')
    op.create_foreign_key(op.f('l1_registration_requests_status_code_fkey'), 'l1_registration_requests', 'master_status', ['status_code'], ['code'])
    op.drop_column('l1_registration_requests', 'status_id')
    op.add_column('l1_registration_remark_history', sa.Column('status_after_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'l1_registration_remark_history', type_='foreignkey')
    op.create_foreign_key(op.f('l1_registration_remark_history_status_after_code_fkey'), 'l1_registration_remark_history', 'master_status', ['status_after_code'], ['code'])
    op.drop_column('l1_registration_remark_history', 'status_after_id')
    op.add_column('dc_remark_table', sa.Column('status_after_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dc_remark_table', type_='foreignkey')
    op.create_foreign_key(op.f('dc_remark_table_status_after_code_fkey'), 'dc_remark_table', 'master_status', ['status_after_code'], ['code'])
    op.drop_column('dc_remark_table', 'status_after_id')
    op.add_column('candidate_table', sa.Column('status_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'candidate_table', type_='foreignkey')
    op.create_foreign_key(op.f('candidate_table_status_code_fkey'), 'candidate_table', 'master_status', ['status_code'], ['code'])
    op.drop_column('candidate_table', 'status_id')
    op.add_column('LMS_table', sa.Column('status_code', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'LMS_table', type_='foreignkey')
    op.create_foreign_key(op.f('LMS_table_status_code_fkey'), 'LMS_table', 'master_status', ['status_code'], ['code'])
    op.drop_column('LMS_table', 'status_id')
    # ### end Alembic commands ###
