"""create_hold_candidate_tb

Revision ID: 85bef9b36dfb
Revises: 57c3c1abf0f5
Create Date: 2026-07-11 23:31:00.450912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85bef9b36dfb'
down_revision: Union[str, Sequence[str], None] = '57c3c1abf0f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
