"""added user profile and is_active

Revision ID: 8a994f9be0c6
Revises: 22c55cbd37ad
Create Date: 2026-07-08 20:02:37.880840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a994f9be0c6'
down_revision: Union[str, Sequence[str], None] = '22c55cbd37ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('LMS_table', 'status_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('candidate_login_table', 'has_changed_password',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('candidate_table', 'status_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.add_column('district_table', sa.Column('registration_open', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('district_table', sa.Column('registration_start_date', sa.String(length=50), nullable=True))
    op.add_column('district_table', sa.Column('registration_end_date', sa.String(length=50), nullable=True))
    op.drop_column('district_table', 'dc_email')
    op.drop_column('district_table', 'dc_name')
    op.drop_column('district_table', 'dc_phone')
    op.create_index(op.f('ix_l1_registration_remark_history_request_id'), 'l1_registration_remark_history', ['request_id'], unique=False)
    op.alter_column('l2_registration_requests', 'unique_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_constraint(op.f('l2_registration_requests_reviewed_by_fkey'), 'l2_registration_requests', type_='foreignkey')
    op.drop_column('l2_registration_requests', 'reviewed_by')
    op.drop_column('l2_registration_requests', 'reviewed_at')
    op.alter_column('nseit_request_table', 'status_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.create_index(op.f('ix_reactivation_documents_request_id'), 'reactivation_documents', ['request_id'], unique=False)
    op.create_index(op.f('ix_reactivation_operators_request_id'), 'reactivation_operators', ['request_id'], unique=False)
    op.create_index(op.f('ix_reactivation_remark_history_operator_id'), 'reactivation_remark_history', ['operator_id'], unique=False)
    op.create_index(op.f('ix_reactivation_remark_history_request_id'), 'reactivation_remark_history', ['request_id'], unique=False)
    op.add_column('user_login_table', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_login_table', 'is_active')
    op.drop_index(op.f('ix_reactivation_remark_history_request_id'), table_name='reactivation_remark_history')
    op.drop_index(op.f('ix_reactivation_remark_history_operator_id'), table_name='reactivation_remark_history')
    op.drop_index(op.f('ix_reactivation_operators_request_id'), table_name='reactivation_operators')
    op.drop_index(op.f('ix_reactivation_documents_request_id'), table_name='reactivation_documents')
    op.alter_column('nseit_request_table', 'status_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.add_column('l2_registration_requests', sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('l2_registration_requests', sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('l2_registration_requests_reviewed_by_fkey'), 'l2_registration_requests', 'user_login_table', ['reviewed_by'], ['id'])
    op.alter_column('l2_registration_requests', 'unique_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_l1_registration_remark_history_request_id'), table_name='l1_registration_remark_history')
    op.add_column('district_table', sa.Column('dc_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('district_table', sa.Column('dc_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('district_table', sa.Column('dc_email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('district_table', 'registration_end_date')
    op.drop_column('district_table', 'registration_start_date')
    op.drop_column('district_table', 'registration_open')
    op.alter_column('candidate_table', 'status_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('candidate_login_table', 'has_changed_password',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('LMS_table', 'status_code',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    # ### end Alembic commands ###
