"""add_admin_login_logs

Revision ID: a410af579e48
Revises: 2134a12ee55a
Create Date: 2026-07-03 14:39:28.387965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a410af579e48'
down_revision: Union[str, Sequence[str], None] = '2134a12ee55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_login_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('admin_type', sa.Enum('chips_admin', 'dc_admin', name='admin_type_enum'), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=False),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_login_logs_lookup', 'admin_login_logs', ['admin_id', 'admin_type', 'is_current'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_login_logs_lookup', table_name='admin_login_logs')
    op.drop_table('admin_login_logs')
    # Drop enum type for Postgres
    op.execute("DROP TYPE admin_type_enum;")
    # ### end Alembic commands ###
