"""add_status_code_to_candidate

Revision ID: d8f0377d4216
Revises: 5ae425ef03a3
Create Date: 2026-06-28 11:15:06.081456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8f0377d4216'
down_revision: Union[str, Sequence[str], None] = '5ae425ef03a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
<<<<<<< HEAD
    pass
=======
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('LMS_table', sa.Column('status_code', sa.String(length=2), nullable=False, server_default='PE'))
    op.drop_column('LMS_table', 'status')
    op.add_column('candidate_table', sa.Column('status_code', sa.String(length=2), nullable=False, server_default='PE'))
    op.drop_column('candidate_table', 'status')
    op.add_column('dc_remark_table', sa.Column('status_after_code', sa.String(length=2), nullable=True))
    op.drop_column('dc_remark_table', 'status_after')
    op.add_column('l1_registration_remark_history', sa.Column('status_after_code', sa.String(length=2), nullable=True))
    op.drop_column('l1_registration_remark_history', 'action')
    op.add_column('l1_registration_requests', sa.Column('status_code', sa.String(length=2), nullable=True, server_default='PE'))
    op.drop_column('l1_registration_requests', 'status')
    op.add_column('l2_registration_remarks', sa.Column('status_after_code', sa.String(length=2), nullable=True))
    op.add_column('l2_registration_requests', sa.Column('status_code', sa.String(length=2), nullable=False, server_default='PE'))
    op.drop_index(op.f('ix_l2_registration_requests_status'), table_name='l2_registration_requests')
    op.create_index(op.f('ix_l2_registration_requests_status_code'), 'l2_registration_requests', ['status_code'], unique=False)
    op.drop_column('l2_registration_requests', 'status')
    op.add_column('lms_remark_table', sa.Column('status_after_code', sa.String(length=2), nullable=True))
    op.drop_column('lms_remark_table', 'status_after')
    op.add_column('nseit_request_remark_table', sa.Column('status_after_code', sa.String(length=2), nullable=True))
    op.drop_column('nseit_request_remark_table', 'status_after')
    op.add_column('nseit_request_table', sa.Column('status_code', sa.String(length=2), nullable=False, server_default='PE'))
    op.drop_column('nseit_request_table', 'status')
    op.add_column('operator_activation_remarks', sa.Column('status_after_code', sa.String(length=2), nullable=True))
    op.add_column('operator_activation_requests', sa.Column('status_code', sa.String(length=2), nullable=False, server_default='PE'))
    op.drop_index(op.f('ix_operator_activation_requests_status'), table_name='operator_activation_requests')
    op.create_index(op.f('ix_operator_activation_requests_status_code'), 'operator_activation_requests', ['status_code'], unique=False)
    op.drop_column('operator_activation_requests', 'status')
    op.add_column('operator_reactivation_requests', sa.Column('status_code', sa.String(length=2), nullable=False, server_default='PE'))
    op.drop_index(op.f('ix_operator_reactivation_requests_status'), table_name='operator_reactivation_requests')
    op.create_index(op.f('ix_operator_reactivation_requests_status_code'), 'operator_reactivation_requests', ['status_code'], unique=False)
    op.drop_column('operator_reactivation_requests', 'status')
    op.add_column('reactivation_operators', sa.Column('status_code', sa.String(length=2), nullable=False, server_default='PE'))
    op.drop_column('reactivation_operators', 'status')
    op.add_column('reactivation_remark_history', sa.Column('status_after_code', sa.String(length=2), nullable=True))
    op.add_column('station_id_remarks', sa.Column('status_after_code', sa.String(length=2), nullable=True))
    op.add_column('station_id_requests', sa.Column('status_code', sa.String(length=2), nullable=False, server_default='PE'))
    op.drop_index(op.f('ix_station_id_requests_status'), table_name='station_id_requests')
    op.create_index(op.f('ix_station_id_requests_status_code'), 'station_id_requests', ['status_code'], unique=False)
    op.drop_column('station_id_requests', 'status')
>>>>>>> origin/mayur
    # ### end Alembic commands ###

def downgrade() -> None:
    pass
