"""Add tracking IDs to L1 Registration

Revision ID: df3f475a05ed
Revises: 6af07a308696
Create Date: 2026-07-04 16:14:32.979470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df3f475a05ed'
down_revision: Union[str, Sequence[str], None] = '6af07a308696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('l1_registration_remark_history', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'l1_registration_remark_history', 'user_login_table', ['author_id'], ['id'])
    op.add_column('l1_registration_requests', sa.Column('dc_id', sa.Integer(), nullable=True))
    op.add_column('l1_registration_requests', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_l1_registration_requests_dc_id'), 'l1_registration_requests', ['dc_id'], unique=False)
    op.create_foreign_key(None, 'l1_registration_requests', 'user_login_table', ['reviewed_by'], ['id'])
    op.create_foreign_key(None, 'l1_registration_requests', 'user_login_table', ['dc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'l1_registration_requests', type_='foreignkey')
    op.drop_constraint(None, 'l1_registration_requests', type_='foreignkey')
    op.drop_index(op.f('ix_l1_registration_requests_dc_id'), table_name='l1_registration_requests')
    op.drop_column('l1_registration_requests', 'reviewed_by')
    op.drop_column('l1_registration_requests', 'dc_id')
    op.drop_constraint(None, 'l1_registration_remark_history', type_='foreignkey')
    op.drop_column('l1_registration_remark_history', 'author_id')
    # ### end Alembic commands ###
