"""convert booleans to integers

Revision ID: e59275b19342
Revises: 8e26e326a712
Create Date: 2026-07-11 16:47:47.283946

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59275b19342'
down_revision: Union[str, Sequence[str], None] = '8e26e326a712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('LMS_table', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('candidate_table', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('l2_registration_requests', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('nseit_request_table', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('operator_activation_requests', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('operator_reactivation_requests', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reactivation_operators', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('station_id_requests', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # Let's drop defaults, alter types and set new defaults
    op.execute("ALTER TABLE admin_login_logs ALTER COLUMN is_current DROP DEFAULT")
    op.execute("ALTER TABLE admin_login_logs ALTER COLUMN is_current TYPE INTEGER USING is_current::integer")
    op.execute("ALTER TABLE admin_login_logs ALTER COLUMN is_current SET DEFAULT 1")

    op.execute("ALTER TABLE candidate_login_table ALTER COLUMN has_changed_password DROP DEFAULT")
    op.execute("ALTER TABLE candidate_login_table ALTER COLUMN has_changed_password TYPE INTEGER USING has_changed_password::integer")
    op.execute("ALTER TABLE candidate_login_table ALTER COLUMN has_changed_password SET DEFAULT 0")

    op.execute("ALTER TABLE candidate_table ALTER COLUMN is_existing_operator DROP DEFAULT")
    op.execute("ALTER TABLE candidate_table ALTER COLUMN is_existing_operator TYPE INTEGER USING is_existing_operator::integer")
    op.execute("ALTER TABLE candidate_table ALTER COLUMN is_existing_operator SET DEFAULT 0")

    op.execute("ALTER TABLE district_table ALTER COLUMN registration_open DROP DEFAULT")
    op.execute("ALTER TABLE district_table ALTER COLUMN registration_open TYPE INTEGER USING registration_open::integer")
    op.execute("ALTER TABLE district_table ALTER COLUMN registration_open SET DEFAULT 1")

    op.execute("ALTER TABLE user_login_table ALTER COLUMN is_active DROP DEFAULT")
    op.execute("ALTER TABLE user_login_table ALTER COLUMN is_active TYPE INTEGER USING is_active::integer")
    op.execute("ALTER TABLE user_login_table ALTER COLUMN is_active SET DEFAULT 1")

    # The columns without defaults:
    op.execute("ALTER TABLE lms_remark_table ALTER COLUMN is_public TYPE INTEGER USING is_public::integer")
    op.execute("ALTER TABLE nseit_request_remark_table ALTER COLUMN is_public TYPE INTEGER USING is_public::integer")
    op.execute("ALTER TABLE otp_verification_table ALTER COLUMN is_verified TYPE INTEGER USING is_verified::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE admin_login_logs ALTER COLUMN is_current DROP DEFAULT")
    op.execute("ALTER TABLE admin_login_logs ALTER COLUMN is_current TYPE BOOLEAN USING (is_current = 1)")
    op.execute("ALTER TABLE admin_login_logs ALTER COLUMN is_current SET DEFAULT TRUE")

    op.execute("ALTER TABLE candidate_login_table ALTER COLUMN has_changed_password DROP DEFAULT")
    op.execute("ALTER TABLE candidate_login_table ALTER COLUMN has_changed_password TYPE BOOLEAN USING (has_changed_password = 1)")
    op.execute("ALTER TABLE candidate_login_table ALTER COLUMN has_changed_password SET DEFAULT FALSE")

    op.execute("ALTER TABLE candidate_table ALTER COLUMN is_existing_operator DROP DEFAULT")
    op.execute("ALTER TABLE candidate_table ALTER COLUMN is_existing_operator TYPE BOOLEAN USING (is_existing_operator = 1)")
    op.execute("ALTER TABLE candidate_table ALTER COLUMN is_existing_operator SET DEFAULT FALSE")

    op.execute("ALTER TABLE district_table ALTER COLUMN registration_open DROP DEFAULT")
    op.execute("ALTER TABLE district_table ALTER COLUMN registration_open TYPE BOOLEAN USING (registration_open = 1)")
    op.execute("ALTER TABLE district_table ALTER COLUMN registration_open SET DEFAULT TRUE")

    op.execute("ALTER TABLE user_login_table ALTER COLUMN is_active DROP DEFAULT")
    op.execute("ALTER TABLE user_login_table ALTER COLUMN is_active TYPE BOOLEAN USING (is_active = 1)")
    op.execute("ALTER TABLE user_login_table ALTER COLUMN is_active SET DEFAULT TRUE")

    # The columns without defaults:
    op.execute("ALTER TABLE lms_remark_table ALTER COLUMN is_public TYPE BOOLEAN USING (is_public = 1)")
    op.execute("ALTER TABLE nseit_request_remark_table ALTER COLUMN is_public TYPE BOOLEAN USING (is_public = 1)")
    op.execute("ALTER TABLE otp_verification_table ALTER COLUMN is_verified TYPE BOOLEAN USING (is_verified = 1)")

    # Restore nullability status
    op.alter_column('station_id_requests', 'status_id', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('reactivation_operators', 'status_id', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('operator_reactivation_requests', 'status_id', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('operator_activation_requests', 'status_id', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('nseit_request_table', 'status_id', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('l2_registration_requests', 'status_id', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('candidate_table', 'status_id', existing_type=sa.INTEGER(), nullable=True)
    op.alter_column('LMS_table', 'status_id', existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
