"""replace_visibility_with_is_public

Revision ID: e90a268f1090
Revises: 06406fff49e1
Create Date: 2026-06-12 17:11:13.684708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e90a268f1090'
down_revision: Union[str, Sequence[str], None] = '06406fff49e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lms_remark_table', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.drop_column('lms_remark_table', 'visibility')
    op.add_column('nseit_request_remark_table', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.drop_column('nseit_request_remark_table', 'visibility')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nseit_request_remark_table', sa.Column('visibility', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('nseit_request_remark_table', 'is_public')
    op.add_column('lms_remark_table', sa.Column('visibility', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('lms_remark_table', 'is_public')
    # ### end Alembic commands ###
