"""Add has_changed_password to UserLogin

Revision ID: f311e745dfaf
Revises: 368cfceb80f6
Create Date: 2026-07-13 12:38:48.973947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f311e745dfaf'
down_revision: Union[str, Sequence[str], None] = '368cfceb80f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login_table', sa.Column('has_changed_password', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_login_table', 'has_changed_password')
    # ### end Alembic commands ###
