import os
import sys
import pandas as pd
import glob

def normalize_district(d):
    if pd.isna(d):
        return d
    d = str(d).strip().upper()
    if d in ['UTTAR BASTAR KANKER', 'UTTAR BASTAR (KANKER)']:
        return 'KANKER'
    if d in ['KABEERDHAAM', 'KABIRDHAM', 'KABIRDHAM (KAWARDHA)']:
        return 'KAWARDHA'
    return d

def is_lwe_district(district_name):
    if not district_name:
        return "No"
    
    d = str(district_name).lower().strip()
    
    lwe_aliases = [
        "bastar", "baster",
        "bijapur",
        "dantewada", "dakshin bastar", "dakshin bastar dantewada",
        "kanker", "uttar bastar", "uttar bastar kanker",
        "narayanpur",
        "sukma",
        "mohla-manpur-chowki", "mohla manpur ambagarh chowki", "mohla manpur", "mohla-manpur-ambagarh chouki"
    ]
    
    for alias in lwe_aliases:
        if alias in d:
            return "Yes"
    return "No"

DIVISIONS = {
    "bilaspur": ["bilaspur", "gaurella-pendra-marwahi", "gaurela-pendra-marwahi", "janjgir-champa", "janjgir", "korba", "mungeli", "raigarh", "sakti", "sarangarh-bilaigarh", "sarangarh"],
    "raipur": ["baloda bazar-bhatapara", "balodabazar", "baloda bazar", "dhamtari", "gariaband", "gariyaband", "mahasamund", "raipur"],
    "durg": ["balod", "bemetara", "durg", "kabirdham (kawardha)", "kabirdham", "kawardha", "khairagarh-chhuikhadan-gandai", "khairagarh", "mohla-manpur-chowki", "mohla-manpur-ambagarh chowki", "mohla", "rajnandgaon"],
    "bastar": ["bastar", "baster", "bijapur", "dakshin bastar (dantewada)", "dantewada", "uttar bastar (kanker)", "kanker", "kondagaon", "narayanpur", "sukma"],
    "surguja": ["balrampur-ramanujganj", "balrampur", "jashpur", "koriya", "manendragarh-chirmiri-bharatpur", "manendragarh", "surajpur", "surguja"]
}

def get_division(district_name):
    if not district_name:
        return "Unknown"
    
    d_name_lower = str(district_name).strip().lower()
    for div, allowed in DIVISIONS.items():
        for a in allowed:
            if a in d_name_lower or d_name_lower in a:
                return div.title()
    return "Unknown"

def generate_mbu_reports(input_file=None):
    if not input_file:
        files = glob.glob('MBU_Entry_Status_District_Wise*.xlsx')
        if not files:
            # check the parent directory if run from scripts/
            files = glob.glob('sample reports/MBU_Entry_Status_District_Wise*.xlsx')
            if not files:
                print("No MBU Excel file found in current directory.")
                return
        input_file = files[0]
        
    print(f"Reading {input_file}...")
    df_mbu = pd.read_excel(input_file)
    
    # Clean up the dataframe similar to MBU.ipynb
    # Usually the headers are in row 2 (index 2)
    df_mbu.columns = df_mbu.iloc[2].values
    df_mbu = df_mbu.iloc[3:].reset_index(drop=True)
    
    # Remove the bottom metadata row if it exists (like Generated By etc.)
    # We will just drop rows where 'District Name' is null or looks like summary
    df_mbu = df_mbu.dropna(subset=['District Name'])
    
    # Remove rows that are not actual data (e.g., '(1)')
    df_mbu = df_mbu[df_mbu['District Name'] != '(1)']
    
    # Normalize district names
    df_mbu['District Name'] = df_mbu['District Name'].apply(normalize_district)
    
    columns_to_aggregate = [
        'Total Student',
        'Total Students AADHAAR Provided',
        'AADHAAR Verified-Passed(Yes)',
        'AADHAAR Verified-Failed(No)',
        'AADHAAR Verified-To be Done',
        'MBU Pending (Age 5-15)',
        'MBU Pending (Age 15 and above)',
        'MBU Not Required',
        'MBU Not Applicable',
        'Status Check to be done'
    ]
    
    # Convert specified columns to numeric
    for col in columns_to_aggregate:
        if col in df_mbu.columns:
            df_mbu[col] = pd.to_numeric(df_mbu[col], errors='coerce').fillna(0)
    
    # Calculate MBU done %
    if 'Status Check to be done' in df_mbu.columns and 'MBU Not Required' in df_mbu.columns and 'Total Student' in df_mbu.columns:
        df_mbu['MBU_done_%'] = ((df_mbu['Status Check to be done'] + df_mbu['MBU Not Required']) / df_mbu['Total Student']) * 100
        df_mbu['MBU_done_%'] = df_mbu['MBU_done_%'].fillna(0).round(2)
        columns_to_aggregate.append('MBU_done_%')
        
    # Group by 'District Name' combining all academic years
    df_final_aggregated = df_mbu.groupby('District Name', as_index=False)[columns_to_aggregate].sum()
    
    # Recalculate MBU done % after aggregation to be accurate
    if 'Status Check to be done' in df_final_aggregated.columns and 'MBU Not Required' in df_final_aggregated.columns and 'Total Student' in df_final_aggregated.columns:
        df_final_aggregated['MBU_done_%'] = ((df_final_aggregated['Status Check to be done'] + df_final_aggregated['MBU Not Required']) / df_final_aggregated['Total Student']) * 100
        df_final_aggregated['MBU_done_%'] = df_final_aggregated['MBU_done_%'].fillna(0).round(2)
        
    if 'MBU Pending (Age 5-15)' in df_final_aggregated.columns and 'MBU Pending (Age 15 and above)' in df_final_aggregated.columns:
        df_final_aggregated['total pending'] = df_final_aggregated['MBU Pending (Age 5-15)'] + df_final_aggregated['MBU Pending (Age 15 and above)']
        columns_to_aggregate.append('total pending')
    
    # Add LWE and Division
    df_final_aggregated['Is LWE District'] = df_final_aggregated['District Name'].apply(is_lwe_district)
    df_final_aggregated['Division'] = df_final_aggregated['District Name'].apply(get_division)
    
    # Create the reports
    os.makedirs('scripts/reports', exist_ok=True)
    out_file = 'scripts/reports/MBU_Reports.xlsx'
    
    # 1. District-wise
    df_district = df_final_aggregated.copy()
    
    # 2. LWE-wise
    df_lwe = df_final_aggregated.groupby('Is LWE District', as_index=False)[columns_to_aggregate].sum()
    if 'Status Check to be done' in df_lwe.columns and 'MBU Not Required' in df_lwe.columns and 'Total Student' in df_lwe.columns:
        df_lwe['MBU_done_%'] = ((df_lwe['Status Check to be done'] + df_lwe['MBU Not Required']) / df_lwe['Total Student']) * 100
        df_lwe['MBU_done_%'] = df_lwe['MBU_done_%'].fillna(0).round(2)
        
    # 3. Division-wise
    df_div = df_final_aggregated.groupby('Division', as_index=False)[columns_to_aggregate].sum()
    if 'Status Check to be done' in df_div.columns and 'MBU Not Required' in df_div.columns and 'Total Student' in df_div.columns:
        df_div['MBU_done_%'] = ((df_div['Status Check to be done'] + df_div['MBU Not Required']) / df_div['Total Student']) * 100
        df_div['MBU_done_%'] = df_div['MBU_done_%'].fillna(0).round(2)
        
    # 4. Combined
    # Sum over everything (dummy column to sum)
    df_combined = df_final_aggregated[columns_to_aggregate].sum().to_frame().T
    df_combined.insert(0, 'Summary', 'Total')
    if 'Status Check to be done' in df_combined.columns and 'MBU Not Required' in df_combined.columns and 'Total Student' in df_combined.columns:
        df_combined['MBU_done_%'] = ((df_combined['Status Check to be done'] + df_combined['MBU Not Required']) / df_combined['Total Student']) * 100
        df_combined['MBU_done_%'] = df_combined['MBU_done_%'].fillna(0).round(2)
        
    with pd.ExcelWriter(out_file) as writer:
        df_district.to_excel(writer, sheet_name='District-wise', index=False)
        df_lwe.to_excel(writer, sheet_name='LWE-wise', index=False)
        df_div.to_excel(writer, sheet_name='Division-wise', index=False)
        df_combined.to_excel(writer, sheet_name='Combined', index=False)
        
    print(f"Reports successfully generated at {out_file}")

if __name__ == '__main__':
    input_file = sys.argv[1] if len(sys.argv) > 1 else None
    generate_mbu_reports(input_file)
