import psycopg2
conn = psycopg2.connect('postgresql://postgres:5171@localhost:5432/chips_db_new')
cur = conn.cursor()
cur.execute('SELECT status_code, COUNT(1) FROM operator_activation_requests GROUP BY status_code')
print('Operator Activation:', cur.fetchall())
cur.execute('SELECT status_code, COUNT(1) FROM candidates GROUP BY status_code')
print('Candidates:', cur.fetchall())
cur.execute('SELECT status_code, COUNT(1) FROM station_id_requests GROUP BY status_code')
print('Station ID:', cur.fetchall())
cur.execute('SELECT status_code, COUNT(1) FROM l1_registration_requests GROUP BY status_code')
print('L1:', cur.fetchall())
cur.execute('SELECT status_code, COUNT(1) FROM l2_registration_requests GROUP BY status_code')
print('L2:', cur.fetchall())
cur.execute('SELECT status_code, COUNT(1) FROM operator_reactivation_requests GROUP BY status_code')
print('Reactivation:', cur.fetchall())
